### ISSUE TITLE
Default to Natural Language Entry Instead of Date / Time Fields

### ISSUE THREAD

**Issue by JimFuoco** [Extended-Thunder/send-later#101]
Can the legacy behavior of triggering send later -> cursor starts in natural language processing field be re-implemented? Either as the default, or as an option? And also CMD+SHIFT+ENTER to place in outbox (related: #50)

Right now it is 2 tabs to get to the date field, which slows things down a bit. My old workflow for an email to be sent same day at 2:05PM would be:

CMD+SHIFT+ENTER (bring up send later)
Type "14:05"
CMD+SHIFT+ENTER (place in outbox)

Now it is more like:
CMD+SHIFT+ENTER (bring up send later)
tab
tab (day)
tab (month)
tab (year)
tab (hour)
type 2
tab (minute)
type 05
tab
type "p"
tab 5x to get to "Send at [date] at 2:05PM"
press enter.

**Comment by jperryhouts** [comment]
Makes sense. I've never been a fan of the natural language parser, but it's definitely easier to tab once from it to the date/time elements than it is to tab all the way through the date/time. I think there would be enough support for this among other users as well. I'll change this after the 8.1.0 release.

> And also CMD+SHIFT+ENTER to place in outbox (related: #50)

Can you explain what you mean by this? Are you describing the same thing as #27 ?

**Comment by jperryhouts** [comment]
This is fixed in the development branch. It won't make it into the upcoming release, but will be in the next one.

**Comment by JimFuoco** [comment]
Yeah I think it's the same thing... I think (and now I'm doubting myself) Command+Shift+Enter would trigger the "Send at [DATE][TIME]" function. Now it doesn't. And Command+Enter sends the message immediately.

**Comment by JimFuoco** [comment]
Tested with the new version today (8.2.1 on TB 78.5.0). Confirming that Shift+CMD+Enter does nothing, and CMD+Enter sends immediately.

**Comment by jperryhouts** [comment]
@JimFuoco Can you open a new bug report for this. That's really a different issue.
