### ISSUE TITLE
Add "{{Time}} minutes from now" functionality

### ISSUE THREAD

**Issue by gyuris** [Extended-Thunder/send-later#103]
I use Send Later (8.1.0) with Mail Merge (7.3.1). I pre Thunderbird 78 era there was a feature that allowed me to send 1 email every 1 minute. I use a CVS file for send data and there is a "Time" column too. I used "{{Time}} minute from now" syntax in "At" form field:

![Képernyőkép erről: 2020-11-13 15-08-20](https://user-images.githubusercontent.com/847982/99080815-1d46e280-25c2-11eb-8797-c802e392a459.png)

Currently this behaviour is broken, I get invalid date:  "X-Send-Later-At: Invalid Date"

**Comment by jperryhouts** [comment]
This sounds like a Mail Merge issue. Alexander Bergmann is the author of Mail Merge. His email address is myaddons@gmx.de.

**Comment by gyuris** [comment]
@jperryhouts thanks for the information. I contacted with him.

A question: Mail Merge should call an internal Send Later function for parsing these smart date formats like "x minutes from now", "tomorom", "in 30 minutes", etc. In pre MailExtensions era this call was:

```
compFields.setHeader("X-Send-Later-At", window.Sendlater3Util.FormatDateTime(sl3dateparse.DateParse(at), true));
```

Is it possible with MailExtension? Or provide a public function?

**Comment by jperryhouts** [comment]
I think this is possible with MailExtensions, but it might not be the simplest way of doing this. I'll contact Alexander this weekend and see if we can work something out.

**Comment by jperryhouts** [comment]
I just implemented all of the backend parts that are needed for mail merge to communicate this information with send later, and I contacted Alexander about it. Should be very little work on his part, so hopefully this will be available in the next versions of send later & mail merge. (of course it has to wait until both come out with new release versions in order to work)

**Comment by gyuris** [comment]
Jonathan, it is a very good news. Thank you for your effort in make this feature.
