### ISSUE TITLE
[TB 78.4.3] Send later button missing 

### ISSUE THREAD

**Issue by despecial** [Extended-Thunder/send-later#104]
After installing 8.1.0 and restarting TB, this is what a new message window looks like for me

![TB 7.4.3 issue](https://user-images.githubusercontent.com/4135109/99092266-360ac480-25d1-11eb-8381-77fc2de16346.png)

**Comment by jperryhouts** [comment]
Right click on the toolbar and use the "Customize" tool to add the button back.
