### ISSUE TITLE
Message sends twice

### ISSUE THREAD

**Issue by vaccoda2020** [Extended-Thunder/send-later#108]
Hi @jikamens 

I have installed Version 8.1.0 (had the beta version installed previously) which appeared to fix the issue with emails not saving to Drafts before they get sent (if set to send-later), however when the email is sent, it gets sent twice.

Not sure if this issue has been experienced / reported by anyone else?

Thanks,

Rob

**Comment by jperryhouts** [comment]
Are they saving to Drafts twice, or is an identical email being sent two times? Are the messages scheduled to recur at all? And do both of the sent messages have the same 'message-id' header?

**Comment by vaccoda2020** [comment]
> Are they saving to Drafts twice, or is an identical email being sent two times? Are the messages scheduled to recur at all? And do both of the sent messages have the same 'message-id' header?

The email will save once to draft, and its the same identical email sending twice. Message only set to send once. 

message ID headers are different it would seem:

**Message-ID: <fe63a42e-3225-c478-c541-924c6f7f4c0b@vaccoda.com>**

and on the second message its:

**Message-ID: <63c616cd-130c-521a-800f-0c61935a8dcd@vaccoda.com>**

Thanks

**Comment by jikamens** [comment]
Are you running Thunderbird on more than one machine at the same time? Do you, perhaps, have a roaming Thunderbird profile (i.e., a Thunderbird profile on a network drive)?

**Comment by vaccoda2020** [comment]
I have my email account on another instance of TB on another computer, and don't have a roaming TB profile.

Thanks,

**Comment by vaccoda2020** [comment]
Just to add, when the (one) email is sent, there will be two instances of the same email showing in "sent" and also 2 instances in "inbox" as mentioned.

Thanks :)

**Comment by jikamens** [comment]
> I have my email account on another instance of TB on another computer, and don't have a roaming TB profile.

Is Send Later installed in both TB instances. Are they both running at the same time?

Have you at any time copied your TB profile from one machine to the other?

I'm trying to figure out if there's any possibility that two different TB instances are sending the message at its scheduled time. Let's cut to the chase: can you reproduce this at a time when you're certain that only one TB instance is running?

**Comment by vaccoda2020** [comment]
Going to close once instance of TB leaving just one running, and will test again - will BRB

**Comment by vaccoda2020** [comment]
So, closing one instance of Thunderbird down, leaving only the other instance running, and then doing a send later only sent one email. 

It looks like running two instances of TB means 2 emails will send - Is that a bug or something to be fixed?

Thanks

**Comment by jikamens** [comment]
Are you running 8.1.0 on both computers or is one of them running the TB68 version of Send Later? That may be relevant.

Code that @jperryhouts introduced in 8.1.0 is supposed to prevent this from happening, but it sounds like it's not working, so I'm going to let him take it from here, since it's his code. ;-)

**Comment by jikamens** [comment]
(Also, if both computers are running TB78, are they both running 8.1.0, or is one of them running an earlier beta? If the latter, can you make sure both are running 8.1.0 and you've restarted TB and see if you can reproduce the issue then when they're both running?)

**Comment by vaccoda2020** [comment]
So the computers are both running TB version 78.4.3 

On one computer, Send Later is version 8.1.0

On the other computer, Send Later is version 8.0.11

Thanks

**Comment by jikamens** [comment]
OK, that's probably what's wrong then. Please upgrade the other computer to 8.1.0 and I believe the problem will go away; this wasn't fixed until 8.0.16. Please confirm.

**Comment by jperryhouts** [comment]
Yes. As @jikamens mentioned, versions <=8.0.15 didn't respect the uuid header so the outdated version is sending messages that it does not own.

**Comment by vaccoda2020** [comment]
Hi guys,

Just updated the version of Send Later to version 8.1.0 on the other computer, ran a test and it only sent one - so problem resolved.

Thanks for the assistance guys - your support and the add-on is outstanding.

Just a side note, are you still continuing to support QuickText? We use this all the time, and happy to continue paying for future updates / funded support, etc.

Thanks for all your help with this!

Rob

**Comment by jikamens** [comment]
We don't have anything to do with QuickText, that's maintained by someone entirely different. :-/

Glad we were able to figure this out for you.

**Comment by vaccoda2020** [comment]
Ooh right - I thought QuickText was supported by you guys somehow?! Must have confused addons!

Apprecate your help - fantastic help and support, and happy to continue paying for ongoing dev / support of Send Later too.

Thanks!

Rob
