### ISSUE TITLE
Setup and send later gui still in mixed languages ;-)

### ISSUE THREAD

**Issue by FinnVonB** [Extended-Thunder/send-later#121]
Hi and thanks for Your great effort in providing this super add on.

The send later button works fine in my TB 78.4.3 (Danish version) after installing newly officially release

BUT

In the Send later gui everything is in English - should be Danish.
The date format is Danish in the 2 boxes where one can set date and time - the box in which the entered date is shown is not Danish format (shows "November 18, 2020 4:23 PM" but should show "18 november 2020 16:23").

Using the settings for send later I get a mix of Danish/ German / Dutch on screen - see attached screenshot
![sendlater](https://user-images.githubusercontent.com/74063304/99552354-333b1580-29bd-11eb-8495-32936f8aeb61.png)
![Sendlater1](https://user-images.githubusercontent.com/74063304/99552357-346c4280-29bd-11eb-884c-552298625c08.png)

There was a similar issue back in May, regarding the settings for version 7.4.4 bug #31

Anything else I can provide let me know

**Comment by jperryhouts** [comment]
Ah, sorry. This slipped my mind because you added the comment to #77 after it had been closed. I think the patch you're referring to in 7.4.4 happened after I forked the 8.x branch, so it must have been missed. I'll fix that this weekend. Thanks for the reminder.

**Comment by jperryhouts** [comment]
This should be fixed by #131
