### ISSUE TITLE
Not working in 64 bit Thunderbird for me

### ISSUE THREAD

**Issue by Windrider6** [Extended-Thunder/send-later#122]
Thunderbird 78.5.0 (64-bit)

In the Write window, if I select File: Send Later, nothing happens.  Same if I use Ctrl-Shift-Enter.

I see no evidence of Send Later anywhere else but a column in the Drafts folder, and in Add-Ons.  No buttons or anything else.

**Comment by jperryhouts** [comment]
For some reason the Send Later button does not always get added to the toolbar automatically. In a message compose window right click on the toolbar and use the "Customize" function to drag Send Later into the toolbar.

The message composition window should look something like this:
![Screenshot from 2020-10-24 15-24-01](https://user-images.githubusercontent.com/6118266/99603492-41d2fe00-29b8-11eb-806e-74800c011945.png)

**Comment by Windrider6** [comment]
I customized the Write toolbar to add "Send Later", and then Send Later worked, including from the File menu.

Testing to be thorough: I then removed that button, and tried Send Later from the File menu.  It didn't work.  Adding the button back, it works again from both the button and the File menu.

So Send Later only works if the button is added to the toolbar in the Write window.

Not a solution, but a **_glitch_**.

**Comment by jperryhouts** [comment]
Not sure what you mean. The new add-on API discourages (and will eventually prohibit) extensions from creating arbitrary new windows, as was possible in the past. So we're being corralled into using these "action" popups instead.

It's certainly a glitch that the button didn't get added automatically, but a Thunderbird glitch not a send later one.

Another related idiosyncrasy is that you need to have the toolbar visible in order for it to work (as is discussed in issue #19). Same situation though, there's not much extensions can do about it.
