### ISSUE TITLE
Nothing happen when selecting the "Send Later" menu item

### ISSUE THREAD

**Issue by syldub69** [Extended-Thunder/send-later#123]
Version 8.1.0 Send Later still not works on TB 78.5.0.
Nothing happen when selecting the "Send Later" menu item !!
The message stays open in edition.
If I use the "Send Later" button from "Send Later Button" addon it does put the message in the local folder "Unsent Messages" !!!

**Comment by jikamens** [comment]
I suspect this is #124. If the Send Later button was is not automatically added to the compose window toolbar, then that's your program. Can you please (a) restart Thunderbird, (b) open a compose window, and (c) check if the "Send Later" button is present on the toolbar in the compose window? If not, then please do the following: (1) open the error console (Tools | Developer Tools | Error Console), (2) right-click on the text area of the console and select Export Visible Messages To | Clipboard, and (3) paste the result into a new comment on #124?

After doing that, to fix this problem so you can use the add-on, you can right-click on the compose window toolbar, select "Customize", drag and drop the Send Later button from the customization palette onto the toolbar, and close the customization palette. Once you've fixed it, the fix should stick.

I apologize for the inconvenience, and thank you for helping us track this down.

if I've misdiagnosed the issue, then please add a comment here indicating that and we'll reopen the issue.

**Comment by syldub69** [comment]
Thanks, you are completely right, this was the cause.
It is solved now after adding the Send Later button in toolbar.
I have posted the Error Console message in #124.
