### ISSUE TITLE
send later doesn't send after 78

### ISSUE THREAD

**Issue by glilienthal** [Extended-Thunder/send-later#139]
I'll try to get as much info together as possible, but apologise in advance if this is not going to be the best bug report ever. 

I am running send later for quite a while, and installed betas after TB 78 came out. 
I am running TB 78.5.0 32 bit on Windows 10 and Sendlater 8.2.1 (but same issue with all betas before)

When I put mails into "send later", they appear in the draft folder, with a send later column giving the exact date I want them to be sent, but they are never actually send. I repeatedly installed and uninstalled several versions of the beta, but this behaviour is unfortunately quite consistent...

If you have an additional  idea on what might help you with solving this, please let me know. 

Thanks in Advance!

Gustav

**Comment by jperryhouts** [comment]
Thank you for the bug report. I think this is almost certainly the same bug as #16, for which we still don't understand the cause, and which we haven't been able to reproduce. If you're up for some investigating there's some discussion in that bug report about things that would be helpful to test.
