### ISSUE TITLE
"Send Later" column re-appears at restart

### ISSUE THREAD

**Issue by despecial** [Extended-Thunder/send-later#158]
Using the latest version of Thunderbird (78.5.0) and this addon, I encounter the following bug.
The "send later" column shows up after restart even though it was de-activated before.

As far as I understood [here](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1426), it's a problem by the timing from TB itself.

Any chance we get your support and maybe remove the column at all or add an option to disable it completely?

<img width="404" alt="Bildschirmfoto 2020-11-25 um 11 59 06" src="https://user-images.githubusercontent.com/4135109/100218915-a391eb80-2f15-11eb-96de-65b2a4a5a2ff.png">

**Comment by jperryhouts** [comment]
What version of Send Later are you using?

I actually copied the Thunderbird-Conversations method for dealing with this, and they should be active in version 8.2.1

**Comment by despecial** [comment]
When I posted, I was using version 8.1.0.
Since there is no info for addon updates, I didnt know there was a new version available.
After upgrading, it looks like it is working fine. Your column doesn't shup up.

Fun thing you mention TB Conversations: I still get their "between" column - so I wonder how their method is not working for their own script.

**Comment by jperryhouts** [comment]
:shrug: The way most add-ons are structured right now is weird, and things like columns require an awkward hybrid between the old and new systems. That introduces a lot unnecessary complexity to the whole thing. Hopefully Thunderbird resolves this soon by just offering a way to do this properly within the new system. Anyway, I'm glad that sorted it out for you!

**Comment by despecial** [comment]
Absolutely. Thanks for the reply and pointing to the right version.
