### ISSUE TITLE
Send Later does not find drafts folder

### ISSUE THREAD

**Issue by jperryhouts** [Extended-Thunder/send-later#165]
Moving this discussion from #16 to its own thread. It appears that in some cases Send Later cannot find a folder with the special type "drafts" for a particular account.

**Comment by jperryhouts** [comment]
@Nerd2k Just picking up the thread from #16 -- Are you still experiencing this problem? If so, could you try running the following code snippet in your console (via the >> input box at the bottom):

    function listFolders(f) { console.log(`  ${f.type}: ${f.path}`); f.subFolders.map(listFolders); }; var ext = window.ExtensionParent.GlobalManager.extensionMap.get("sendlater3@kamens.us"); var apiCan = [...ext.views][0].apiCan; apiCan.findAPIPath("accounts").list().then(accts => accts.map(a => { console.log(a.name); a.folders.map(listFolders); }));

That should output something like the following:

```
Local Folders debugger eval code:1:311
  drafts: /Drafts debugger eval code:1:35
  trash: /Trash debugger eval code:1:35
  outbox: /Unsent Messages debugger eval code:1:35
jph@extended-thunder.org debugger eval code:1:311
  inbox: /INBOX debugger eval code:1:35
  undefined: /[Gmail] debugger eval code:1:35
  sent: /[Gmail]/Sent Mail debugger eval code:1:35
  archives: /[Gmail]/All Mail debugger eval code:1:35
  junk: /[Gmail]/Spam debugger eval code:1:35
  undefined: /[Gmail]/Starred debugger eval code:1:35
  undefined: /[Gmail]/Important debugger eval code:1:35
  drafts: /[Gmail]/Drafts debugger eval code:1:35
  trash: /[Gmail]/Trash debugger eval code:1:35
  drafts: /Drafts debugger eval code:1:35
  undefined: /Trash
```

It prints the name of each account and then loops over all its sub-folders, printing each folder's "type" and name. In theory each account should have at least one folder whose type is "drafts". Let me know what happens in your case, because it sounds like send later is not finding that.

If the problem has gone away, let me know that as well.

**Comment by Nerd2k** [comment]
Hi, sorry for the delay!

This is the output of the script:

```
23:32:29.599 XXX debugger eval code:1:305
23:32:29.600   undefined: /XXX debugger eval code:1:35
23:32:29.600   templates: /Drafts debugger eval code:1:35
23:32:29.601   undefined: / 2 debugger eval code:1:35
23:32:29.602   undefined: /XXX debugger eval code:1:35
23:32:29.603   inbox: /INBOX debugger eval code:1:35
23:32:29.603   undefined: /XXX debugger eval code:1:35
23:32:29.604   sent: /sent debugger eval code:1:35
23:32:29.604   trash: /Trash debugger eval code:1:35
```

It looks as if my drafts folder is not of type "drafts" but of type "templates". So probably Send Later needs to look for folders like that as well.

**Comment by jperryhouts** [comment]
That's weird. At least in principle that should be an easy fix (fixed by #188), but I worry a little about the process of removing messages after they have been sent. Right now Send Later reads the message, decides if it should send it, creates a new message in the outbox folder with the same contents, than deletes the original (and possibly creates an updated one for recurring messages).

That should all be fine, but the delete function relies on the message URI following a particular pattern. I'm positive that pattern is always used for Drafts, and I assume it's used in other folders, but I don't really understand what template folders are so I worry that the assumption won't hold. I added a safety check for that in #189, but there's still the possibility of it just leaving the original message in Drafts.

I'm attaching a zipped package of the current development version here. Give that a shot and let me know if it works.
[send_later-8.5.2.zip](https://github.com/Extended-Thunder/send-later/files/5613405/send_later-8.5.2.zip)

**Comment by jperryhouts** [comment]
I've done more poking around, and it looks like this pattern is the same for all folder types, so this patch should work in all cases.

Question: Does the "send later" column show up in your drafts folder?

**Comment by Nerd2k** [comment]
Thank you for your investigation! Ok so I will just wait until version 8.5.2 becomes available through the official update channel and give it a go.

Re "send later" column in the drafts folder: yes, it shows up. (this is version 8.4.5)
