### ISSUE TITLE
Send Later - Date and Time wrong

### ISSUE THREAD

**Issue by reinhard512** [Extended-Thunder/send-later#18]
Thunderbird 78.3.1 with Send Later 8.0.3 uses incorrect format of date and time.
Emails sent by send later habe been rejected by some Providers (e.g. gmx.net) stating "Make sure that your mail server and client time and date are correctly set as specified in RFC 5322".
Emails sent directly without send later are accepted by same providers.

Header of eMail sent directly contains date and time as follows:
"Wed, 30 Sep 2020 17:17:30 +0200" 

Header of eMail sent by send later contains date and time as follows:
"2020-09-30T17:24:21+02:00"

According RFC 5322 time zone should be 4DIGIT, which means +0200 instead of +02:00 - please correct in future release of send later.

Best regards

**Comment by jperryhouts** [comment]
Thank you for catching that. This likely explains the SMTP rejection that was mentioned in #16 as well. I'll patch this over the weekend.

**Comment by jperryhouts** [comment]
Fixed by #20. Will be included in next release.

**Comment by reinhard512** [comment]
Tested version 8.0.5 and problem is solved. Thank you for your efforts. I really like send later. 

Best regards
