### ISSUE TITLE
Composition toolbar hidden breaks SendLater.

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#19]
SendLater 8.0.3 (beta)
Thunderbird 78.3.1 (Linux)

"Send Now" gives:
```
Uncaught TypeError: aDocumentNode.cardDetails is undefined
    UpdateExtraAddressProcessing chrome://messenger/content/msgHdrView.js:1517
    updateExtraAddressProcessing chrome://messenger/content/mailWidgets.js:1225
    OnAddressBookDataChanged chrome://messenger/content/msgHdrView.js:416
    OnAddressBookDataChanged chrome://messenger/content/msgHdrView.js:410
    onItemPropertyChanged chrome://messenger/content/msgHdrView.js:404
    notifyItemPropertyChanged resource:///modules/AddrBookManager.jsm:484
    modifyCard resource:///modules/AddrBookDirectory.jsm:950
    expandRecipients chrome://messenger/content/messengercompose/MsgComposeCommands.js:6993
    GenericSendMessage chrome://messenger/content/messengercompose/MsgComposeCommands.js:4386
    SendMessage chrome://messenger/content/messengercompose/MsgComposeCommands.js:4855
    doCommand chrome://messenger/content/messengercompose/MsgComposeCommands.js:982
    doCommand chrome://messenger/content/messengercompose/MsgComposeCommands.js:1163
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messengercompose/messengercompose.xhtml:1
msgHdrView.js:1517:1
[Exception... "[JavaScript Error: "aDocumentNode.cardDetails is undefined" {file: "chrome://messenger/content/msgHdrView.js" line: 1517}]'[JavaScript Error: "aDocumentNode.cardDetails is undefined" {file: "chrome://messenger/content/msgHdrView.js" line: 1517}]' when calling method: [nsIAbListener::onItemPropertyChanged]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: resource:///modules/AddrBookManager.jsm :: notifyItemPropertyChanged :: line 484"  data: yes] AddrBookManager.jsm:484:20
Received onBeforeSend from tab 
Object { id: 14, index: 0, windowId: 288, highlighted: true, active: true, status: "complete", width: 860, height: 663, mailTab: false }
background.js:323:11
Received keycode cmd_sendLater background.js:279:11
```

"Send Later" gives:
```
Received keycode cmd_sendLater
```
In neither case does the SendLater pop-up window appear.

**Comment by jperryhouts** [comment]
Can you verify which settings you have enabled? In particular, do you have "Send does Send Later" enabled, and "Console log level" set to "Debug", "Trace", or "All"?

The log entry you posted doesn't appear to be a Send Later error, although it might indicate that Send Later is not being properly activated when you open the composition window. If your log level is set to "Debug" or higher you should see the cheeky message "Binding to send later events like a barnicle" when you open a new message composition window. Regardless of your settings, clicking the "Send Later" menu item should open the dialog.

Are you able to open the Send Later dialog with the button in the compose window toolbar?

**Comment by Geremia** [comment]
@jperryhouts 

Here it is with the log level set to "All":

"Send Now":
```
Received onBeforeSend from tab 
Object { id: 23, index: 0, windowId: 428, highlighted: true, active: true, status: "complete", width: 860, height: 663, mailTab: false }
background.js:323:11
INFO [SendLater]: Send does send later. Opening popup. static.js:15:13
```
"Send Later":
```
Received keycode cmd_sendLater background.js:279:11
```

> Are you able to open the Send Later dialog with the button in the compose window toolbar?
Yes.

**Comment by jperryhouts** [comment]
Ah, I see. Unfortunately this is a bug in Thunderbird. I've opened a bug report for it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1669118 but several similar bugs have been open in Firefox for years. Thunderbird development seems agonizingly slow sometimes, so I don't know when it will be fixed.

I'll add more helpful debug log messages for this, and I'll try to think of a meaningful workaround, but in the mean time you'll just have to leave the toolbar open when scheduling messages. I'll leave this github issue open until it's solved one way or another.

**Comment by Geremia** [comment]
@jikamens  Also, ctrl+enter doesn't trigger the "Send at" button.

**Comment by jperryhouts** [comment]
> Also, ctrl+enter doesn't trigger the "Send at" button; it re-triggers the "Send Later" button.

This is different from the composition toolbar bug, Could you open a new issue for this?

**Comment by Geremia** [comment]
@jperryhouts Yes: #27

**Comment by Geremia** [comment]
With version 8.0.11, "Send now" and "Send later" both don't make the pop-up window appear. Only clicking the "Send Later" button works.

**Comment by jperryhouts** [comment]
Workaround in version 8.2.1 will force the toolbar to display. Not really a fix for this bug since I realize some people don't want the toolbar, but unfortunately Send Later just won't work without it so here we are.
