### ISSUE TITLE
Formatting of pop-up and shortcut keys

### ISSUE THREAD

**Issue by JimCarls** [Extended-Thunder/send-later#194]
Will we be getting a "prettified" version of Send-Later soon? It still looks like a draft right now, but more important: I have it set to "Send = Send later" but I keep pressing Alt-N for messages I want to then send immediately, and there's no hot key to do that any more.  ;-)

**Comment by jperryhouts** [comment]
Shortcut keys are enabled in the 8.5 release, which will be available on ATN later in the week. You can also download it from the [release page](https://github.com/Extended-Thunder/send-later/releases). Not sure what you mean by prettified, but you're welcome to submit a pull request if you have a preferred layout.
