### ISSUE TITLE
No Attachment Send Later Loops back and forth unless Thunderbird footer dismissed

### ISSUE THREAD

**Issue by winedog** [Extended-Thunder/send-later#198]
Noticed a bug today with 8.4.5 Send Later.

If I go use the 'Send Now' function in the Send Later dialogue with an email where Thunderbird gives the 'Did you forget to attach a file' warning and then choose 'No, send now',  Send Later and Thunderbird just loop back and forth endlessly.  However, if you dismiss the footer that also warns about the missing attachment, then Send Now via Send Later works.

Not a show stopper bug, but thought I should raise the issue here!

**Comment by jperryhouts** [comment]
This should be fixed in the latest release. Go to the extension manager page, and use the `gear icon > Check for updates` to upgrade to version 8.5.3. You will have to restart Thunderbird for that upgrade to take effect.
