### ISSUE TITLE
Owl for Exchange comatibility

### ISSUE THREAD

**Issue by Botislav** [Extended-Thunder/send-later#199]
From Thunderbird v78 forward "Owl for exchange" Add-on became urgent for my everyday use. Unfortunately "sent-alter" Add-on  can't send out an email from drafts folder on exchange server where it puts it.

**Comment by jperryhouts** [comment]
What makes you think this is related to Owl for Exchange? Does Send Later work with another account, but not an Exchange account? What version of Send Later are you using?

**Comment by Botislav** [comment]
I can't test another account due to company rules. It is all blocked. Till Thunderbird v78 with IMAP incoming server and SMTP Send Later worked fine. From v78 IMAP was not working anymore, so I was forced to change to Exhange using "Owl for Echange" Add-on. That combination does not work with Send Later anymore.
I'm using Thunderbird 78.1.5 (32-bit), Owl for Exchange 0.77 and Send Later 8.5.3

I tried to use same configuration on home comp with gmail account and other my (non Exchange) accounts and it worked fine.

**Comment by jperryhouts** [comment]
Can you describe again what combinations do and don't work. Did you try Send Later on version 78 before switching to Exchange, or did you make both of those changes at the same time?

What happens when you uninstall the send later add-on, and use the built-in send later funcion? It should save messages directly into the outbox, and then be triggered to send with the `File > Send Unsent Messages` menu.

**Comment by jperryhouts** [comment]
I don't know if it's still the case, but [Exchange used to strip send later headers out of messages](https://blog.kamens.us/send-later/#bad-mail-servers).

You can check this when you schedule a message, and then go look at it in the drafts folder, does a date show up in the send later column? When you select the draft message and view its source (Ctrl+U) are there any headers that start with "x-send-later"?

If it looks like those headers are being removed, you can set Thunderbird to use the Drafts folder in your local storage through the `Edit` > `Account settings` > `Copies & folders` > `Drafts and Templates`. Set "Keep draft messages in:" option to "Drafts folder on `Local Folders`".

**Comment by jperryhouts** [comment]
I just discovered and patched a bug that might be related to this in #204 -- I submitted the patched version to Thunderbird for review and it should be available soon. It is in version 8.5.4.

**Comment by Botislav** [comment]
I just tested everything you described.
1. Send Later sends message to Draft folder on Exchange server
  Three X-Send-Later headers are there
  X-Send-Later-Uuid: {5d3ab432-f409-41be-a4a3-120760319fb9}
  X-Send-Later-At: Fri, 04 Dec 2020 20:23:00 +0100
  X-Send-Later-Recur: none
Messages stuck in folder and never leave it . OK, ia have few masseges for more than a week there now.

2. Changing Drafts folder to local folder
  Three X-Send-Later headers are there
  X-Send-Later-Uuid: {5d3ab432-f409-41be-a4a3-120760319fb9}
  X-Send-Later-At: Fri, 04 Dec 2020 20:28:00 +0100
  X-Send-Later-Recur: none
Messages are sent out like charm.

**Comment by jperryhouts** [comment]
Cool. Glad it's working for you. Once version 8.5.4 is available you ~~should~~ *might* be able to switch your drafts folder back to the exchange server, but you can always leave it this way if it's all the same to you.
