### ISSUE TITLE
Catch 22 - not sending with "Check Spelling before Sending"

### ISSUE THREAD

**Issue by sds-i** [Extended-Thunder/send-later#203]
Hi, 
Version 8.5.3. sends me into the endless loop with the setting of "Check Spelling before Sending".
I think that had disappeared in 8.4.8 or so, not sure.
Regards and thanks for the hard work
Christian

**Comment by sds-i** [comment]
I re-set everything and re-started all and it seems to work now.
I also turned off all other Add-ons.
It could be that I had this problem because I transferred the Thunderbird profile to a new partition after extending my internal SSD.

**Comment by jperryhouts** [comment]
Huh. Could certainly be related to restarting after the upgrade. Add-ons are finicky about that these days, and probably will continue to be for a while. Glad it seems to be working. Let me know if that changes.
