### ISSUE TITLE
Send Later should not save draft when opened for editing unless it has Send Later headers!

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#208]
It appears that Send Later is now saving draft messages whenever they are opened for editing, even if they didn't have any Send Later headers in them. This is... not good.

**Comment by jperryhouts** [comment]
Certainly not as slick, and worth fixing, but is this actually a problem? I can't imagine why it would make a difference for non-scheduled messages but I must be forgetting some other use case.

**Comment by jikamens** [comment]
Would you say this:

>but is this actually a problem?

If the message had 10MB worth of attachments and you were working over a slow internet connection?

**Comment by jperryhouts** [comment]
Just wondering if this was serious enough to be blocking. I'm with you that it should be fixed, just making sure I didn't miss something obvious that was going to break things for someone.

**Comment by jikamens** [comment]
Don't think it's a blocker.
