### ISSUE TITLE
"Send Now" button does not work when "'Send' does 'Send Later'" preference is enabled

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#209]
1. Enable the "'Send' does 'Send Later'" option.
2. Open a compose window and fill in the recipient address, subject, and body.
3. File | Send Later or Ctrl/Cmd-Shift-Enter.
4. Click "Send Now" button.

Note that nothing happens.

The "Send Now" button should send the message immediately.

Kinda sorta workaround: specify "now" in the text box and click the "Send at" button.

**Comment by jperryhouts** [comment]
Are you on the development branch? I can't reproduce this.

**Comment by jikamens** [comment]
I am on trunk.

**Comment by jperryhouts** [comment]
Any console errors?

**Comment by jikamens** [comment]
Just this when I click the "Send Now "button, which doesn't seem to be coming from Send Later:

![image](https://user-images.githubusercontent.com/1598067/101233831-baa8aa00-3688-11eb-8bef-b88ce220e776.png)

**Comment by jperryhouts** [comment]
Does the popup close, or just stay there? Does the send now button work when "'Send' does 'Send Later'" is not enabled? What about the "Put in Outbox" button?

**Comment by jikamens** [comment]
The popup disappears.

The button does work when "'Send' does 'Send Later'" is not enabled.

The "Put in Outbox" button works.

**Comment by jperryhouts** [comment]
I don't have any ideas off the top of my head for why this would be happening, but it's getting late. I'm gonna sleep on this and look into it tomorrow.

**Comment by jperryhouts** [comment]
I still don't know why this would have been happening, but I shuffled a lot of stuff around related to how sending works in #217 -- let me know if this is still happening with those changes.

**Comment by jikamens** [comment]
Can no longer reproduce with trunk.
