### ISSUE TITLE
Scheduled messages not being delivered for me

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#212]
Currently on the trunk, scheduled messages are not being delivered for me. I see this in the error console:

![image](https://user-images.githubusercontent.com/1598067/101233675-81bc0580-3687-11eb-87ad-154692c73765.png)

**Comment by jperryhouts** [comment]
Does this happen for all messages, or only some? Is this preceded by a debug message like `getRawMessage.streamListener.OnStopRunning received #### bytes  (exitCode: ###)`, and if so what's the error code?

**Comment by jikamens** [comment]
Also seeing this shortly after scheduling a message:

![image](https://user-images.githubusercontent.com/1598067/101233889-12471580-3689-11eb-9b2d-9dedcca80d15.png)

This seems more consistent than the errors I pasted above.

**Comment by jikamens** [comment]
There is no OnStopRunning message that I can see.

**Comment by jperryhouts** [comment]
Might need the console log level set higher. But more importantly does this happen for all messages or just some?

The first screenshot was probably more relevant, since that comes from the main loop iterating over drafts. The other messages are mostly harmless, and some are not from send later (background.mjs.js is something else).

**Comment by jikamens** [comment]
Isn't happening for all messages.

Started send later with several scheduled messages, some sent, some did not.

Entire log attached.

I see errors such as: ERROR [SL3U]: Error reading message imap-message://jik@jik4.kamens.us/Drafts#13713, onStartSending called with zero messages, this._copyProcess is null.

[logs.txt](https://github.com/Extended-Thunder/send-later/files/5646498/logs.txt)

**Comment by jikamens** [comment]
Restarted Thunderbird with four scheduled messages. Three of them were past due to be sent, one was in the future. Two of the past-due messages were sent, one was not. The one that was not generated the "Error reading message iamp-message:..." error. I also saw "onStartSending called with zero messages" and "this._copyProcess is null" again.

**Comment by jikamens** [comment]
Is it possible that the message not being sent on startup is due to the fact that Thunderbird hasn't yet finished connecting to the IMAP server when Send Later tries to read the first message so it fails?

**Comment by jikamens** [comment]
With the log level turned up:

![image](https://user-images.githubusercontent.com/1598067/101234292-e4170500-368b-11eb-8efb-2e6e2c9bd54c.png)

**Comment by jikamens** [comment]
I actually think there are two different problems here.

The first is that it appears that when Send Later is trying to read a draft right when Thunderbird starts up it fails to read the draft successfully and never retries so the draft never gets sent. This generates errors like the ones I've pasted above.

The second is that it appears that messages I am scheduling are not being sent at their scheduled send times until I quit and restart Thunderbird. This doesn't cause any errors, the messages just aren't sent.

This appears to be true for _all_ messages, nothing I'm scheduling is being sent until I quit and restart Thunderbird.

Note that Send Later knows about the scheduled messages -- they are being included in the "PEND" count at the bottom -- they just aren't being sent.

**Comment by jikamens** [comment]
Aha.

Figured it out, I think.

Stand by, I need to confirm.

**Comment by jperryhouts** [comment]
Is it doing its main loop at all? When the console log level at "All" it is very chatty during that process, so should be obvious when that happens.

> Is it possible that the message not being sent on startup is due to the fact that Thunderbird hasn't yet finished connecting to the IMAP server when Send Later tries to read the first message so it fails?

This seems likely. If it fails the first time around because of an incomplete imap connection, and then doesn't execute its main loop then it will never have a chance to re-try those messages.

The messages about `onStartSending called with zero messages`, and  `this._copyProcess is null.` are harmless. They come from the "send unsent messages" part of the experiment script. Based on some comments I saw in the v7.x code I added a second-pass to execute the send unsent messages routine a second time to be sure nothing gets left in the outbox. Most of the time that is unnecessary, so it complainins that it was asked to send unsent messages when there wasn't anything there to send.

**Comment by jikamens** [comment]
OK, just pushed a fix.

The issue is that you weren't respecting the hidden checkTimePref_isMilliseconds preference, which I had set to true (you migrated that setting from my legacy preferences). I had the interval set to 15000, which should have meant every 15 seconds, but instead it was being interpreted as every 15000 minutes.

If it had been working properly then the fact that a message wasn't being read properly on startup wouldn't matter because it would be read properly on the next pass through the main loop.

There is one thing I don't understand so I'm not closing this issue yet. This line means that it's impossible to set an interview smaller than 1 minute:

```
    interval = Math.max(1, interval);
```

I'm not sure why it's there, but it doesn't play nicely with `checkTimePref_isMilliseconds`. Even if I set that pref to true and my interval to 15000, which should result in a check every 15 seconds, I only get a check once per minute.

What is that `Math.max` protecting against? Can that line just be removed?

**Comment by jperryhouts** [comment]
If you set checkEvery = 0, then send later doesn't process drafts (user suggested this as an easier way to disable sending for use with a separate server running thunderbird). But the loop should still happen in case the user turns 'checkEvery' back on -- or, really should be just switched off and then re-activated by listening to changes on storage.local.

But, simplest solution is to just replace the `interval =` line with something like

```
interval /= preferences['checkTimePref_isMilliseconds'] ? 1000 : 1;
if (interval === 0)
  interval = 1;
```
