### ISSUE TITLE
Send later encrypts emails - not ok / GPG

### ISSUE THREAD

**Issue by ilippert** [Extended-Thunder/send-later#272]
Version
8.0.7

I compose a message and declare that the message should NOT be encrypted. Then define a date to send it later. So far so good.
When the message is eventually sent, it is sent encrypted to myself to the correspondents.

**Comment by jph-sendlater** [comment]
Please upgrade to the latest version of Send Later (8.7.2), and check [here](https://github.com/Extended-Thunder/send-later/discussions/200) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1681168) for information about why that happened, and what's being done about it.

**Comment by tomasi-o** [comment]
Is still happening with v 8.7.6 on Thunderbird 78.8.0 (macOS 10.13.6)

**Comment by jph-sendlater** [comment]
@tomasi-o Are you sure you're not talking about #200 ?
