### ISSUE TITLE
Send Later disabling itself during automatic updates

### ISSUE THREAD

**Issue by jph-sendlater** [Extended-Thunder/send-later#274]
This one is pretty enigmatic, but for some users it seems that the Send Later extension has quietly been disabled in the background. This seems to happen during an automatic update, but it's not clear why or how.

This is likely resolved by #273, but I don't know for sure.

**Comment by tplanter** [comment]
I have had the same experience. 
I seem to remember the old version of Send Later (pre v78) used to notify you when it had been updated, but I may not be remembering correctly. If it was so, can we have the function back?
If we don't get told when an update has occurred, it's difficult to know that a restart of Thunderbird is required to re-activate the extension.

**Comment by jph-sendlater** [comment]
That's part of the problem here: There doesn't seem to be a reliable way to do that.

For context, Webextension add-ons are supposed to be "restartless", because they are supposed to live in neat little sandboxes that Thunderbird can start/stop/cleanup with relatively little fuss. But of course most of Send Later's functionality doesn't exist in that API yet, so big parts of it exist outside of the sandbox. This leaves all kinds of ways for wires to get crossed during upgrades. It used to be that extensions could flag themselves as "legacy" mode, which told Thunderbird that they did need to be restarted, but now that's no longer an option -- Thunderbird treats all extensions as restartless, whether or not they really should be treated as such.

There's a poorly documented API that supposedly blocks updates until the next restart. I heard about it from the MailMerge author last Fall, and I implemented it at some point a while back. It shouldn't cause anything like this, but that's my primary suspect at this point.

#273 *reverts* that behavior, to allow automatic updates without a restart. That risks things not cleaning up properly during upgrades, but any misbehaviour that would cause would be superficial UI stuff, and far less disruptive than quietly disabling with no warning. We won't know if it worked until two releases from now, though, since that change will only take effect when upgrading *from* the next release version.

**Comment by hameau** [comment]
> #273 _reverts_ that behavior, to allow automatic updates without a restart. That risks things not cleaning up properly during upgrades, but any misbehaviour that would cause would be superficial UI stuff, and far less disruptive than quietly disabling with no warning. We won't know if it worked until two releases from now, though, since that change will only take effect when upgrading _from_ the next release version.

Just for clarity, from which version of SL will this be effective? My installation just upgraded from v8.7.2 to v8.7.3 and SL was silently disabled.

**Comment by jph-sendlater** [comment]
If #273 does fix this problem, then it will be effective when Send Later upgrades **from** version 8.7.3.

I *really* hope that does work, because the fact this only happens during ATN upgrades, and only for some people, means this will be extremely hard to track down with anything but slow guess-and-check patches. I'll ping you (by commenting here) next time I push an update to check on that.

**Comment by jph-sendlater** [comment]
@hameau I've uploaded a new patch version to ATN (version 8.7.5) with a very minor bug fix. Let me know whether Send Later still disables itself once TB auto updates.

**Comment by hameau** [comment]
Only a sample size of 1, but today's update from v8.7.3 to v8.7.5 went smoothly and Send Later remained enabled afterwards.

**Comment by jph-sendlater** [comment]
That's great news! @tplanter I'm not sure if you upgraded to 8.7.3, but if so did the latest upgrade to 8.7.5 go smoothly?

**Comment by tplanter** [comment]
Yes, I've upgraded too. All seems to be working well, no issues with disabling or resetting the composition window, thanks :)

**Comment by jph-sendlater** [comment]
Fantastic! I'm closing this issue now, but let me know if it comes up again.
