### ISSUE TITLE
Relative time display not localized

### ISSUE THREAD

**Issue by DenB10** [Extended-Thunder/send-later#285]
The more accurate display of relative time introduced in version 8.7.3 leads to a regression in localization: this relative time in brackets is in English and is not translated. ( "2.7 hours from now" and not "dans 2.7 heures" as expected in French for example)
Best regards,
DenBar

**Comment by jph-sendlater** [comment]
Thanks for the heads up! This is fixed by 823ad5031baa4967adacd1ed47039f604cd200ab in patch version [8.7.5](https://github.com/Extended-Thunder/send-later/releases/tag/8.7.5).
