### ISSUE TITLE
Messages are transfered from Draft to Unsent folder, without leaving TB

### ISSUE THREAD

**Issue by Djoe689** [Extended-Thunder/send-later#292]
Hi,

When I'm scheduling a new message, I can see it in the Draft folder, with the right value in the "send later" column.
At the schedule time, the message is transferred to the "Unsent" folder without never leaving TB.

Here below the error (xxx replace my profile) :

WebExtensions: ERROR [SL3U]: SendLaterFunctions.queueSendUnsentMessages Error triggering send from unsent messages folder. 
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgSendLater.sendUnsentMessages]", result: 2147500037, filename: "jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/bjs1bi5z.default-release/extensions/sendlater3@kamens.us.xpi!/experiments/sl3u.js", lineNumber: 290, columnNumber: 0, data: null, stack: "queueSendUnsentMessages@jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/bjs1bi5z.default-release/extensions/sendlater3@kamens.us.xpi!/experiments/sl3u.js:290:28\n", location: XPCWrappedNative_NoHelper }

I don't know if it can help, but the issue appear when I transfer my TB's profile from a computer to another (W7 to W10, fresh install on W10 with TB 78.7.1 64bits and sendlater 8.7.6).

Thank you

**Comment by jph-sendlater** [comment]
Thank you, that is helpful. Can you check what happens when you use `File > Send Unsent Messages` (with a message already in the "unsent" folder)?

**Comment by Djoe689** [comment]
"File > Send Unsent Messages" is grey, I cannot select it :
- I have a message on Unsent folder
- and I'm not offline ("File > Offline > Work offline" is not ticked)
TB issue?

**Comment by jph-sendlater** [comment]
It sounds like it. The error you're seeing from send later is coming from a TB internal function (or rather from a piece of code that's duplicated from Thunderbird), so there's some regression in Thunderbird that seems to be blocking that built-in function from working. I'll look around on Bugzilla to see if anyone's reported it and let you know what I find.

**Comment by Djoe689** [comment]
Problem solved, don't look around I'm writing the solution in the next post.

**Comment by Djoe689** [comment]
The issue was the content of "mail.accountmanager.defaultaccount" registry.
Before update, it was containing "account3".
But I have no "account3" in my registry, we can check it by looking for "mail.account.account" in the search field.

In my case this search return nothing for "account3", but I have a value for "account4":
mail.account.account4.identities;id2

To know who is "id2" account you have to search to "mail.identity.id2.useremail".
It return for me:
mail.identity.id2.useremail;my_email_address@awesome.sendlater.plugin

So I have :
- modified "mail.accountmanager.defaultaccount" value to "account4"
- quit and restart TB
- TB ask me if I want to send unsent message :-)
- Then I tried to schedule a new message, and everything go went well !

Thank you for you first comment, I didn't realize that this issue came from TB and not you plugin :-)

**Comment by Djoe689** [comment]
I don't know how to close this issue, perhaps I don't have this right.
This issue can be close.

**Comment by jph-sendlater** [comment]
Thank you for tracking that down! I've been corresponding with another user about the same problem, but he didn't have much technical background so remote debugging was slow-going. I'll let him know how to fix it, and I'll put something about it in the documentation.

Thanks again!

**Comment by hemanti0503** [comment]
I had this issue, as well. Thank you so much for posting how to solve it, @Djoe689! :)

For reference: My setting was mapped to account16, which does not have any identity connected to it. Changed it to account1, which does have an associated ID, and everything works fine now.
