### ISSUE TITLE
Enhancement: Allow users to customize the date/time format

### ISSUE THREAD

**Issue by jph-sendlater** [Extended-Thunder/send-later#294]
As the title says, it would be great to have the option to bypass the system locale settings for things like date/time formats.

**Comment by devscheffer** [comment]
> 
> 
> As the title says, it would be great to have the option to bypass the system locale settings for things like date/time formats.

I like to use the format 2021-02-27 24:00:00.
Could you put the option to change the format?

**Comment by jph-sendlater** [comment]
The idea would be to allow setting any format your heard desires, with a strftime format string like `%Y-%m-%d %H:%M:%S` in your case. This isn't particularly high priority for me at the moment, though, so it might not happen very soon.

**Comment by jph-sendlater** [comment]
Implemented as part of #319
