### ISSUE TITLE
Old API needs to be updated

### ISSUE THREAD

**Issue by phassanm** [Extended-Thunder/send-later#296]
The add-on needs to be limited in its permissions instead of the current "Have full, unrestricted access to Thunderbird, and your computer". As the current status is not safe in the long term.

Ref. https://support.mozilla.org/ru/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer

**Comment by jph-sendlater** [comment]
See #250
