### ISSUE TITLE
Message doesn't leave drafts when returning to online

### ISSUE THREAD

**Issue by dmusican** [Extended-Thunder/send-later#300]
A common scenario I use is that I queue up a message for sending later, and then am offline when the time comes around (perhaps Thunderbird is closed, or I've selected "Work Offline"). When I go back online -- by starting Thunderbird or by deelecting "Work Offline" -- if I have messages that are past their send time, I am correctly prompted if I want to send the messages now. When I say yes, the messages are sent, but they are not removed from my Drafts folder; they seem to just rot their after the fact. 

(This is not a problem when I am online when the message expects to be sent. In that case, the message sends, and is removed from Drafts automatically as expected.)

**Comment by jph-sendlater** [comment]
Are you positive the messages are being sent at all? The "would you like to send unsent messages" dialog shows up when you start Thunderbird (ore return to online) and there are already messages in your outbox.

**Comment by dmusican** [comment]
I just tried this again: yes, the email is being sent. I scheduled an email for delivery about 3 minutes into the future (sending to an alternative email that I have). I then shut down Thunderbird, waited 5 minutes, and then started Thunderbird up again. I got the prompt asking to send unsent messages, and I said to send now. The message was sent, I see a copy of it in my Sent Mail folder, and my alternative email account did in fact receive the email. But the "send later" draft of that email is still in my Drafts folder.

**Comment by dmusican** [comment]
Followup: I am only reliably having this problem when Thunderbird is shutdown, and then restarted; I'm having more trouble duplicating it when keeping Thunderbird open, and going offline in between. Here's some of the errors from the console. Does this help?

``` 
 2021-03-09 11:31:56	sendLaterModule	ERROR	onStartSending called with zero messages

Log4moz.jsm:766
    append resource:///modules/gloda/Log4moz.jsm:766
    log resource:///modules/gloda/Log4moz.jsm:416
    error resource:///modules/gloda/Log4moz.jsm:424
    onStartSending resource:///modules/activity/sendLater.jsm:169
    onStopSending jar:file:///home/dmusicant/.thunderbird/pk3xb7a9.2020-09-30/extensions/sendlater3@kamens.us.xpi!/experiments/sl3u.js:548
2021-03-09 11:31:56	sendLaterModule	ERROR	onStartSending called with zero messages


TypeError: this._copyProcess is null
sendLater.jsm:233:13
    onMessageSendProgress resource:///modules/activity/sendLater.jsm:233
    onStopSending jar:file:///home/dmusicant/.thunderbird/pk3xb7a9.2020-09-30/extensions/sendlater3@kamens.us.xpi!/experiments/sl3u.js:548
ERROR [SendLater]: Attempted to resend message "try again 4" <9e95f8ee-7045-72cb-9c2f-e112c701b495@carleton.edu>. static.js:44:13
    logger moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:44
    error moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:48
    possiblySendMessage moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/background.js:200
An error occurred in SL3U.doConfirmCheck: TypeError: Services.prompt.clertCheck is not a function ExtensionCommon.jsm:743
    normalizeError resource://gre/modules/ExtensionCommon.jsm:743
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1011
ERROR [SendLater]: Error: An unexpected error occurred static.js:44:13
    logger moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:44
    error moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:48
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:127
    getActivity resource://gre/modules/ActivityManager.jsm:127
    removeActivity resource://gre/modules/ActivityManager.jsm:80
    onFolderRemovedFromQ resource:///modules/activity/autosync.jsm:244
    _timerCallback resource:///modules/AppIdleManager.jsm:30
TypeError: prin.URI is null
ConduitsParent.jsm:123:58
Error: Unknown sender or wrong actor for recvCreateProxyContext ConduitsParent.jsm:321:13
DEBUG [SendLater]: Adding function element ReadMeFirst static.js:44:13
DEBUG [SendLater]: Adding function element BusinessHours static.js:44:13
DEBUG [SendLater]: Adding function element DaysInARow static.js:44:13
DEBUG [SendLater]: Adding function element Delay static.js:44:13
ERROR [SendLater]: Attempted to resend message "try again 4" <9e95f8ee-7045-72cb-9c2f-e112c701b495@carleton.edu>. static.js:44:13
    logger moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:44
    error moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:48
    possiblySendMessage moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/background.js:200
An error occurred in SL3U.doConfirmCheck: TypeError: Services.prompt.clertCheck is not a function ExtensionCommon.jsm:743
    normalizeError resource://gre/modules/ExtensionCommon.jsm:743
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1011
ERROR [SendLater]: Error: An unexpected error occurred static.js:44:13
    logger moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:44
    error moz-extension://41209dc4-6bac-4c51-b080-8c71d4d03227/utils/static.js:48
```

**Comment by jph-sendlater** [comment]
I'm not positive what's going on, but it looks like you might have a corrupted drafts folder. Try following the steps here:
https://extended-thunder.github.io/send-later/#corrupt-drafts-error

Let me know if that improves things at all.

**Comment by dmusican** [comment]
Thanks, I tried the above (going through identities, then repairing folders), but the problem still occurs.

**Comment by jph-sendlater** [comment]
I'm still puzzled by the prompt you're getting when you start Thunderbird. That prompt is supposed to show up if you have messages already in your outbox, not if they are currently in your Drafts folder and about to be moved to the outbox (i.e. that message comes from Thunderbird, not from the Send Later extension).

* Try checking the outbox (Local Folders / Outbox) before you quit Thunderbird next time. Is there anything in there?
* When you see the 'you have unsent messages' alert next time you start Thunderbird, click "no" and check what's in the outbox.
    - Check the timestamps on whatever messages are in the outbox. Are they current, or do they indicate the messages were put there before you shutdown Thunberbird.

Neither of those really explains why anything would get abandoned in the Drafts folder, but they might give clues.

**Comment by dmusican** [comment]
Thanks: I've got it figured out, after a fashion. It's not directly related to what you asked, @jph-sendlater, but you pointed me in the right direction. It's a combo of bugs, as the hard ones often are.

I finally bit the bullet and rebuilt my profile, again. (Seems like I'm doing this every six months.) I think having a clean profile helped a bit with reliability on what was going on.

Here's what's happening: *sometimes*, Thunderbird keeps running in the background when I shut it down. I can't determine quite what's driving it; I think it's related to the cb_thunderlink addon I'm also running, but it's not reliably giving consistent results. I can see that via a `ps` command, or, if I start thunderbird from the command line, I can see that the prompt doesn't come back.

So... what's going on is that when this happens, Thunderbird isn't hung, but it's still doing something. If it's in this background zombie-like state, Send Later is apparently still running. And if Thunderbird was offline at the time (i.e., I left it in that state when I tried to shut it down), Send Later kicks in, finds itself without a GUI, and seems to just dump the draft into the outbox. Eventually, when I return to Thunderbird by starting it up again, Thunderbird prompts me because it finds the message in the Outbox that Send Later dumped into it. But, when Thunderbird is in this half-alive state and Send Later runs, it doesn't seem to empty the message from the Drafts folder.

So I obviously have some of my own mess to clean up regarding figuring our why Thunderbird isn't quite shutting down properly. (I'm having minimal luck there, but that's a different issue.) However, it seems that Send Later may not be handling this completely gracefully. Is it possible that if Thunderbird is offline, and if the GUI "isn't there," that Send Later may be dumping the message into the Outbox and not deleting it from Drafts? And if so, is that a bug that should be fixed?

**Comment by jph-sendlater** [comment]
Wow, nice work tracking that down. This would obviously be hard to debug to find the true cause since at the time the error is happening you've ostensibly already closed Thunderbird.

Send Later's function for deleting the draft is indeed separate from the function for placing it in the Outbox. That's intended to be a safety in case something goes wrong while copying to the outbox- at least then the original is not lost.

My guess is that the only thing Send Later could do here would be to more proactively attempt to delete messages if it finds stale drafts hanging around. However, I would prefer to err on the side of caution when it comes to deleting anything. Stale messages are definitely better than unintentional deleted ones.

For now I'd prefer to keep things as is unless this behavior becomes more wide spread. I'm going to close this issue for now, but I'll keep an eye out for anything similar in the future, and let me know if you do discover any more details about this in the future.

**Comment by dmusican** [comment]
Thanks, that's super helpful. It helps me to know there's an explanation for it -- and what it is --- as I'll also worry less about if the messages actually got sent.
