### ISSUE TITLE
v8.0.6 is incompatible with CardBook 52.4

### ISSUE THREAD

**Issue by SHC22** [Extended-Thunder/send-later#31]
When "SendLater 8.0.6" is installed together with "Cardbook 52.4", menu items from Cardbook are displayed incorrectly. With version 8.0.5 the problem does not occur.

![1](https://user-images.githubusercontent.com/42532064/95978734-db881800-0e1a-11eb-989d-03394d583646.jpg)
![2](https://user-images.githubusercontent.com/42532064/95978737-dc20ae80-0e1a-11eb-84a1-bc39b858c985.jpg)

Thanks,
SHC

**Comment by SHC22** [comment]
The problem also exists in v8.0.7.
Thanks, 
SHC

**Comment by jperryhouts** [comment]
I figured out why this happens. It looks like both Send Later and CardBook use a similar hack to handle locales outside of their MailExtension sandbox. They both check if they have access to a `browser.i18n` object, and create a mock one if not.

Send Later beats CardBook to the punch with defining a mock `browser.i18n` object, and so when Cardbook goes to generate localized strings it tries to use the Send Later translations, which of course don't include the right values (`__CARDBOOKMSG_.*_`).

CardBook plays nicer than Send Later in that it never tries to create its own `browser.i18n` object, and instead just creates a pointer to the global one if it exists. Over the weekend I plan to follow suit, and implement something similar in Send Later, which should fix this issue.

**Comment by SHC22** [comment]
Thanks a lot! I really appreciate your effort!
SHC

**Comment by jperryhouts** [comment]
This should be fixed by #42 . I will generate an updated release later this weekend, but I'm hoping to close out more bug reports before I do that.

**Comment by jperryhouts** [comment]
Note: It appears that Cardbook doesn't always do this properly either. The screenshot below is in a vanilla Thunderbird profile without Send Later installed.

![Screenshot from 2020-10-24 13-34-48](https://user-images.githubusercontent.com/6118266/97093041-cc188400-15fd-11eb-9d7e-0b412767a0ac.png)

**Comment by SHC22** [comment]
Hi,
I may not understand all technical details. But at the moment the problem exists in version 8.0.9, too.
SHC

**Comment by jperryhouts** [comment]
Could you send a screenshot? For me there are still places where Cardbook does not properly insert localized strings, but that also happens without Send Later. The main ones in the Cardbook tab appear correctly for me with 8.0.9.

**Comment by SHC22** [comment]
Hi,
Yes of course:

![CardBook](https://user-images.githubusercontent.com/42532064/97116143-79bd8d00-16fb-11eb-88d2-9d055baa5a4c.jpg)

When I downgrade to Sendlater 8.0.5 it looks 'normal'.

Thanks,
Christian

**Comment by jperryhouts** [comment]
Very strange. Maybe has something to do with which locale is selected. I don't know why English would behave any differently, but that's the only relevant difference between your setup and mine I can think of at the moment.

I'm reopening this issue, and I'll look into it more this week. Unfortunately I won't have much time to work on it until next weekend. Sorry for the inconvenience.

**Comment by ovari** [comment]
> Note: It appears that Cardbook doesn't always do this properly either. The screenshot below is in a vanilla Thunderbird profile without Send Later installed.
> 
> ![Screenshot from 2020-10-24 13-34-48](https://user-images.githubusercontent.com/6118266/97093041-cc188400-15fd-11eb-9d7e-0b412767a0ac.png)

Is @CardBook aware of this? Thank you

**Comment by CardBook** [comment]
next Cardbook version will solve this issues of toolbar : https://gitlab.com/CardBook/CardBook/-/issues/986#note_439525365

**Comment by jperryhouts** [comment]
Sounds like this mystery is solved then? @SHC22 let me know if this persists after the next cardbook version is released

**Comment by SHC22** [comment]
Hi, 
yes - the problems seems to be solved. THANKS!
SHC
