### ISSUE TITLE
PGP and Send Later don't work

### ISSUE THREAD

**Issue by EWB1857** [Extended-Thunder/send-later#310]
With Thurnderbird 78.9.1 PGP can be enabled. I created a key but did not encrypt emails. I created an OpenPGP key using Thunderbird. 

Send Later placed an error in the draft folder noting Encryption Errors. The OpenPGP key was revoked. Made no differnce. The OpenPGP key was deleted from Thunderbird. Made no difference. Once an OpenPGP key has been created, Thunderbird allocates a Configuration Key (cannot be deleted ... can only be changed) and while this exists, Send Later raises the Encryption Errors.

Normal emails can be send ant received (so far as my testing has been done).

It seems that Send Later and OpenPGP, even if not used for emailm encryption, are incompatible. Is this correct?

**Comment by jph-sendlater** [comment]
Yep, that's the case. See here for more details: https://github.com/Extended-Thunder/send-later/discussions/200
