### ISSUE TITLE
Default Recurrence After Editing Message

### ISSUE THREAD

**Issue by Shimergo** [Extended-Thunder/send-later#314]
Hi,
It used to be that after editing a recurring message (from my Drafts folder) and hitting 'Send Later' again, then the preset date and recurrence rule was the same as before. Perfect! But now it resets the default date to '5mins from now' with no recurrence. So there's the wee hassle of setting it all up again, and the danger I've forgotten to note when the next due date was and recurrence rule.
Can the old user-friendly functionality be restored? Or is there a new trick to getting it to do this?
I'm on version 8.7.7, which AFAIK is the default with TB 78.7.1 on Linux Mint 20.
Thanks!

**Comment by jph-sendlater** [comment]
This is on my radar: https://github.com/Extended-Thunder/send-later/issues/290

**Comment by Shimergo** [comment]
#290 is too techy for me :) , but I know for sure it did used to restore schedule parameters when editing saved/ waiting messages. Thanks - I'll wait patiently for the fix!
