### ISSUE TITLE
Send-Now marks a message replied while Send-Later does not

### ISSUE THREAD

**Issue by wuhandong** [Extended-Thunder/send-later#32]
![replied](https://user-images.githubusercontent.com/36207248/96160236-4d279b00-0edb-11eb-8d33-9e01f4b2b036.jpg)

If I reply to a message using send-now, it marks the message as "replied" (see the backward arrow on the Test 1 message in the attached screenshot); if I reply to a message using send-later, it does not mark the message as "replied", even after the delayed message is sent out by SL (see Test 2 message in the screenshot; this was after the delayed response was already sent).

**Comment by jikamens** [comment]
I don't think this is an "enhancement". This functionality exists in the TB68 version of Send Later so if it doesn't exist in the TB78 version then that's a regression and therefore a bug.

**Comment by jperryhouts** [comment]
I'm reserving the bug label for issues that are critical to fix before an ATN release. This is more of a high-priority non-priority at the moment. Most of the issues with an 'enhancement' label are in that category right now.

It would be nice if github would use some sort of more granular ranking system for relative importance of issues, but for now this falls below that critical cutoff so I'm leaving it as is until after the ATN release.

**Comment by jikamens** [comment]
To reduce ambiguity you might want to consider creating a new label such as "high priority" or "blocker" for the issues that you believe block ATN release, and so that you can don't have to overload "enhancement".

**Comment by jperryhouts** [comment]
That's a good idea. I'll reshuffle things after the release.

Ideally there would be a system for tagging issues that didn't communicate a value judgement on the merit of the issue itself. I always feel weird applying tags for that exact reason, but they're so useful for prioritizing. 'Unconfirmed' is another awkward one. There needs to be something else that describes "sounds like a problem, but I haven't figured out why it happens yet" as is the case for #16 and #31 for instance.

**Comment by jperryhouts** [comment]
Fixed in #132
