### ISSUE TITLE
Send later field disappears

### ISSUE THREAD

**Issue by bharada** [Extended-Thunder/send-later#320]
I am using Send Later 8.7.7 on Thunderbird 78.10.0.  When I schedule a message to be sent later, the message will initially appear in my drafts folder with the send later field reflecting the scheduled time that the email should be sent.  However, the information in that field will later disappear, and the message will not be sent at the scheduled time.  The send later function seems to work because if I schedule the email to be sent after 5 min, the function works.  The problem seems to be that the send later information essentially disappears after the email has sat in the drafts folder for a few hours.  Any information about how to resolve this issue would be appreciated.

**Comment by jph-sendlater** [comment]
The draft folder column has always been finicky, but I made a bunch of changes to it recently that will hopefully make it more reliable. Those will be included in the next release version (8.9.2) which is just waiting on Thunderbird developers to review and approve it. Let me know once you're on the new version if things are still acting up.

**Comment by jph-sendlater** [comment]
Version 8.9.2 is out now. Please upgrade and let me know if the column is still misbehaving. You might want to restart Thunderbird as well, just for good measure.

**Comment by cestmoimeme** [comment]
I have the last version (8.9.2 from april 30 2021) and  the "sendlater" column in drafts is empty
I restarted thunderbird (78.10.0) , and also my computer and emptied the PRAM 
Thank yo for your job !

**Comment by jph-sendlater** [comment]
@cestmoimeme I think your issue is not the same as the original issue. I'll respond in the discussion you opened.

@bharada Sorry I initially misunderstood your issue. Is the behavior you described reproducible, or does it seem to be intermittent?

**Comment by bharada** [comment]
Hi @jph-sendlater,

I updated to Send Later 8.9.2 over the weekend and had scheduled a message to be sent this morning.  The send later field did not depopulate as previously observed, but the message was not sent at the scheduled time.  I'll check if this error reproduces.

**Comment by bharada** [comment]
I scheduled two messages to send later yesterday, one after 15 min and one after ~24 hrs.  The 15 min one was sent fine, on schedule, but the 24 hour message was not sent and remains in my drafts folder, so the problem is reproducible and the update did not fix the issue.

**Comment by jph-sendlater** [comment]
Hm. This might prove to be challenging to track down, since it happens at some undetermined time. I'll look into this more over the weekend and let you know what I find.

**Comment by jph-sendlater** [comment]
I'm wondering if the schedule actually disappears, or if Send Later somehow stops recognizing these messages even though they're still valid.

@bharada would you please check one of the affected messages for the following: open its source text by viewing the message in the drafts folder and clicking Ctrl+U. Does it have a header called "X-send-later-at"?

Also, does the status indicator at the bottom of the main window (where it says "Send Later [...]" indicate that the message is still active? i.e. When you first schedule a message it will say 'Send Later [PEND 1]', but does it return to 'Send Later [IDLE]' after some time?

By the way, it's possible to inadvertently cancel a message by opening it as if you're going to edit it. You should see a warning popup when that happens unless you've opted out of that warning before. It's probably not the case here, but just something to be aware of.

**Comment by bharada** [comment]
Note that my version of Thunderbird recently updated to 78.10.1

I scheduled a message a few days ago.  The Send Later column for this message is currently empty in the drafts folder, and the status bar says "Send Later [IDLE]."  If I view the message with Ctrl+U, I do not see a "X-send-later-at" header. (With an earlier test message, however, it was not sent despite the send later column showing the scheduled send time and IIRC, the status bar did indicate pending messages).

**Comment by bharada** [comment]
Ok, I seemed to have caught the problem occurring.

I scheduled a message to be sent later and placed it in my draft folder at 3:16p today.  At the time, the status bar said "Send Later [PEND 1]." It is now 4:06p, and now the status bar says "Send Later [IDLE]."  The scheduled date for sending the message still appears in the "Send Later" column of the drafts folder, but Ctrl+U does not show any "X-send-later-at" lines in the message header.

Hopefully this information helps you narrow down the problem.  Let me know if any additional information would be helpful.

**Comment by bharada** [comment]
I was able to resolve the issue by following the instructions described here: https://extended-thunder.github.io/send-later/#send-later-doesnt-work-with-mail-servers-that-discard-its-x-send-later-headers

I'm accessing a Microsoft Exchange email, which apparently removes the "X-send-later-at" headers.  Switching my drafts folder from the drafts folder on the Exhcange serve to a local folder resolves the issue.
