### ISSUE TITLE
Send Later column empty in Drafts folder

### ISSUE THREAD

**Issue by unode** [Extended-Thunder/send-later#325]
Initially reported by @cestmoimeme in https://github.com/Extended-Thunder/send-later/issues/320#issuecomment-831164821

I'm experiencing the same issue.
The "Send Later" button still displays the time when clicked.
The left side of the header also only shows "Send Later" without additional info, which makes it look a out of place.

![screenshot_2021-05-05_21-20-15_384170276](https://user-images.githubusercontent.com/122319/117209417-964b2800-adf6-11eb-8aa8-693ce8557ed9.png)

**Comment by jph-sendlater** [comment]
The fact that the 'send later' header row is empty is a good clue, because those two elements share some code. I'll look into this over the weekend and let you know what I find.

**Comment by jph-sendlater** [comment]
@unode and @cestmoimeme would you mind testing out this patch when you have a chance?
https://github.com/Extended-Thunder/send-later/releases/tag/8.9.3

Just download the .xpi file, then open the 'Add-ons Manager' tab in Thunderbird and either drag the .xpi into the window or use the gear icon > "Install Add-on From File..." to install it.

I added a fallback for the column text values which should at least prevent leaving the column blank. If the fallback is active then it will be limited to only displaying the next send time. It will not show information about whether the message is scheduled to recur, and it will not be able to display errors like "this message is encrypted" or "scheduled by another client". I figure this is still better than being blank, though.

Anyway, look for three things:
1. Is the column still blank?
2. Do the column values end with an asterisk? The fallback value will show a date/time followed by a `*`.
3. Is the message header displayed? i.e. when you're viewing a message is there a "Send Later" row below "To:", "Subject", "Date", etc.? Is it blank? (Note: I didn't change anything in that code for now, so it would be surprising if it isn't blank)

**Comment by cestmoimeme** [comment]
the column is still blank (I close my thunderbird and my session to be sure) 
<img width="416" alt="sil1" src="https://user-images.githubusercontent.com/17205394/117496175-f36de780-af76-11eb-97fc-ecbc2d2be0a9.png">

when I'm opening a message in drafts, it looks like that (with the "send later button on right) but nothing in the row "envoyer plus tard" (send it later)  below "copie à" (copy to) 
<img width="989" alt="sil2" src="https://user-images.githubusercontent.com/17205394/117496190-f963c880-af76-11eb-810f-f170c5b8b647.png">
and at the botoom of the screen the number of "send later" messages is ok 
<img width="426" alt="sil3" src="https://user-images.githubusercontent.com/17205394/117496266-18625a80-af77-11eb-8a42-8ec432e37d8e.png">
(I've got 8 messages in my draft floder, all to send later)
thank you for your help

**Comment by unode** [comment]
### Version installed
![screenshot_2021-05-07_21-14-48_641584746](https://user-images.githubusercontent.com/122319/117497835-48126200-af79-11eb-9f14-00a3ce8d73fe.png)

### Message list
![screenshot_2021-05-07_21-14-04_324039841](https://user-images.githubusercontent.com/122319/117497850-4a74bc00-af79-11eb-9de5-43fc39ec2366.png)

### Headers
![screenshot_2021-05-07_21-13-44_704454529](https://user-images.githubusercontent.com/122319/117497859-4d6fac80-af79-11eb-862c-8998fc9b7c08.png)

There's a slight header misalignment visible in the last screenshot (`From` not aligned with other fields) but otherwise seems to work for me.

**Comment by unode** [comment]
Another perhaps related issue is that the "Send Later" header is also visible in folders other than "Drafts".
Immediately after installing the add-on only the "Drafts" folder shows this header.
Restarting Thunderbird again shows the header in all folders.

**Comment by jph-sendlater** [comment]
I've decided to just revert all the recent changes to the UI components for version 8.9, which should solve this for you. Please give the latest release a try and let me know if you see the same issues https://github.com/Extended-Thunder/send-later/releases/tag/8.9.4

**Comment by cestmoimeme** [comment]
Fantastic !Great !!! It's ok again, the column is back ... To be sure, I closed my session, reboot my computer, emptied the memory and yes, it's ok !
Thanks a lot

**Comment by unode** [comment]
Indeed, same here.

**Comment by unode** [comment]
I think we are ok with closing this issue.
Thanks a lot for the quick action and the fix.

Cheers!
