### ISSUE TITLE
9.0.0 -- telling me on exit there are messages scheduled to be sent when there aren't

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#327]
Using Send Later 9.0.0 on the current Thunderbird beta (89.0b3), when I quit from Thunderbird on macOS with Command-Q, I get, "Scheduled messages warning - Send Later // There are messages scheduled to be sent. Send Later can only send messages when Send Later is running. Are you sure you want to exit?" There are in fact no messages scheduled to be sent, and the Send Later status at the bottom of the window says "IDLE".

**Comment by jph-sendlater** [comment]
This should be fixed by 8cff438da6de787d59f245f18ae433b653844a53
