### ISSUE TITLE
Blank controls with macOS 89.0b4 (64-bit)

### ISSUE THREAD

**Issue by beefstew** [Extended-Thunder/send-later#333]
89.0b4 (64-bit)

The Send Later button appears, but after clicking it none of the GUI widgets are visible.

The cursor changes on hover to hand and text input line, which suggests that something is working, but the display is all white.

![Screen Shot 2021-05-28 at 2 18 41 AM](https://user-images.githubusercontent.com/2262454/119938856-0747b080-bf5b-11eb-9f1a-f7c29f59c3c9.png)

Thanks,
Chris

**Comment by jph-sendlater** [comment]
Are you on a mac by any chance? This is the same as #328 which I'm certain is a Thunderbird issue. There's a bug report open for it, but I haven't heard anything about it in a couple weeks: https://bugzilla.mozilla.org/show_bug.cgi?id=1710608

**Comment by beefstew** [comment]
Yes, I am on a Mac. This issue I opened looks like duplicate.
