### ISSUE TITLE
No email sent and "Encryption compatibility issue" in the Send Later column of the Drafts folder

### ISSUE THREAD

**Issue by AlainRnet** [Extended-Thunder/send-later#336]
Hello.
Under Linux (elementary-OS), Thunderbird was updated last week (I think from 68.10.0 to 78.8.1) and now Send Later no longer works (after update ; now : 8.9.4), the following message appears in the Send Later column of the Drafts folder: Encryption compatibility issue

Could this have something to do with abandoning Enigmail in favour of the system implemented in Thunderbird?

After re-anabling Enigmail, nothing changes, no email sent with the Send Later module.

**Comment by AlainRnet** [comment]
I have done other tests and I confirm that when I do not select any key from the account settings in Thunderbird, Send Later works correctly.

**Comment by jph-sendlater** [comment]
This is an issue with how Thunderbird deals with encryption now that enigmail is part of the main code base.
https://github.com/Extended-Thunder/send-later/discussions/200
