### ISSUE TITLE
Display updates in status bar from background processes

### ISSUE THREAD

**Issue by jperryhouts** [Extended-Thunder/send-later#34]
Re-implementing legacy functionality to keep user better informed of Send Later status.

**Comment by jikamens** [comment]
This isn't just about the status. It's also about the fact that clicking on the status in the status bar popped up a useful menu. Would be nice to put back the words "Send Later" in the status bar even if it doesn't indicate status and just provides that menu.

**Comment by tplanter** [comment]
I just used the latest version of Send Later for the first time (installed and functioning without issue this time!) and was surprised not to see a status message appear telling me how many messages were in the Send Later queue.
It made me check the draft folder to confirm that I had initiated Send Later for the message.
I'd love to see that status report restored.

**Comment by jperryhouts** [comment]
This is fixed in [version 8.5.1](https://github.com/Extended-Thunder/send-later/releases/tag/8.5.1)
