### ISSUE TITLE
Problems after upgrading to 8.9.4

### ISSUE THREAD

**Issue by ferranb** [Extended-Thunder/send-later#343]
Hi,

First of all. Congrats for your very useful Send Later add-on. Its really great!

After automatically upgraded to 8.9.4, Send Later stop working and no longer send messages.

Looking on the console shows this cosntantly:

Uncaught Error: Extra arguments in function ufunc:ProperMes finished
    sendlater3 kamens.us.xpi!/utils/static.js:860
    sendlater3 kamens.us.xpi!/experiments/headerView.js:146
    sendlater3 kamens.us.xpi!/experiments/headerView.js:171

I guess the problem is the custom function ProperMes I created (and worked well) on earlier version... but I cannot select the function in the Function Editor..

I've dropped the funcion from sendLater2/ufunc directory but the error continues. Where are located the reference?

Best regards!

**Comment by jph-sendlater** [comment]
Check the "Dynamic Function Editor" section in the extension preferences page.

I'm about to head out of town for the week. Sorry this response is terse, but if you're still having trouble with this when I return I'll get back to you with more specific help.

**Comment by ferranb** [comment]
Not shown in the "Dynamic Function Editor" section in the extension preferences page. Thats the stranger thing.

**Comment by ferranb** [comment]
Finally I uninstalled, cleaned the sendLater directory and reinstalled. Now it works
