### ISSUE TITLE
Problem in offline use

### ISSUE THREAD

**Issue by musenbaron** [Extended-Thunder/send-later#355]
I am often out and about without the Internet. If I try to send e-mails while doing this, an error message appears - logical, but I also cannot use the Send later function.

**Comment by jph-sendlater** [comment]
This should work fine. What happens when you try to schedule a message with Send Later?

**Comment by jph-sendlater** [comment]
Since it's been over a month I'm going to go ahead and close this issue. Let me know if you're still having problems with this.
