### ISSUE TITLE
Never sends

### ISSUE THREAD

**Issue by sharkmullet** [Extended-Thunder/send-later#356]
I haven't changed any settings, but it stopped working about 4 days ago.

My email goes into the drafts, but it never sends it.  It sits in the draft box with the correct time in the "send later' column, but it sits there past that time and never goes out.

Is it user error?

**Comment by jph-sendlater** [comment]
Did you solve your problem? If not, try starting with the troubleshooting steps here: https://extended-thunder.github.io/send-later/#troubleshooting
