### ISSUE TITLE
GMX rejecting all scheduled mails

### ISSUE THREAD

**Issue by reinhard512** [Extended-Thunder/send-later#368]
Since September 1, 2021 german mail-provider gmx.net rejects all mails, sent via sent later. Mails sent directly are accepted.
I am using Send Later version 8.9.5 since July 25, 2021 with Thunderbird 78.13.0 since August 10, 2021 and I did not notice this problem before.
Here is the general explanation of GMX for the rejection: https://www.gmx.net/mail/senderguidelines/
Most likely is a problem with Date/Time format. However, comparing the headers of a scheduled and a directly sent mail I could not see any difference.

**Comment by jph-sendlater** [comment]
Can you tell me more about your configuration, and what exactly happens when you send a message with send later? Did anything change about your configuration or setup since the last time Send Later worked properly?

Also, does the built-in send later function work? (i.e. schedule the message using the "place message in outbox" button, then use `File > Send Unsent Messages` to send it). If that doesn't work, then there might be a configuration issue in your SMTP settings.

**Comment by reinhard512** [comment]
If I send a message with send later to a none-GMX address everything works as expected -> mail sent at scheduled time.
If I send a message with send later to a GMX address, it is sent at scheduled time. Only moments later I receive a mail from my mail server (my provider) "Returned mail" with following content (email-adresses changed):
----------------------------------------------------------
From: MAILER-DAEMON@smtp.myprovider.de
Re.: Returned Mail: Test
To: my address@mydomain.de

*** MAILVERSAND FEHLERBERICHT ***

Die E-Mail wurde eingeliefert am Donnerstag, 2. September 2021 09:26:40 +0200 (CEST)
von Host [192.168.0.51]   .

Betreff: Test
Absender: my address@mydomain.de

Der Mailversand zum folgenden Empfänger ist endgültig gescheitert:

adressee@gmx.de
   Letzter Fehler: 554 5.0.0 
   Erklärung: host mx01.emig.gmx.net [212.227.17.5] said: Transaction failed Reject 
              due to policy restrictions. For explanation visit 
              https://www.gmx.net/mail/senderguidelines?ip=81.169.146.21
              6&c=hd

   Auszug aus dem Session-Protokoll:
   ... während der Kommunikation mit dem Mailserver mx01.emig.gmx.net [212.227.17.5]:
   >>> DATA (EOM)
   <<< 554 Transaction failed Reject due to policy restrictions. For 
       explanation visit 
       https://www.gmx.net/mail/senderguidelines?ip=81.169.146.216&c=hd
----------------------------------------------------------
Tested with quite some different GMX-addresses, always same result -> mail rejected due to policy restrictions. 

I did not change anything since the last time Send Later worked properly.
My configuration: Thunderbird 78.13.0 with add-ons "Send Later" and "Lookout". Both actual versions.
Thunderbird starts automatically with Windows and runs all day in the background. Normally I use "replace send with send later ", but I disabled this feature right now. All other settings are standard.

If I use the built-in send later as described by you it works. Message is not returned.

**Comment by jph-sendlater** [comment]
Interesting. When you get a chance, please try the following experiment, and let me know what you find:

1. Compose a message, and use the "place message in outbox" button to put it directly in the outbox
2. Disable the Send Later preference "trigger unsent message delivery from outbox"
3. Compose an identical message to before, but schedule it with Send Later and wait for it to get moved to the outbox
4. Compare the raw headers of the two messages in your outbox, and look for any differences

**Comment by jph-sendlater** [comment]
Actually, I just ran that experiment myself and I do notice a few differences. I'll look into this later this afternoon and let you know what I find.

**Comment by jph-sendlater** [comment]
It looks like the Javascript locale manager uses "Sept" as the short version of September, but the RFC specifies "Sep". That would explain why messages started failing on September 1 (and why this hasn't been a problem before, since the current date/time format function was [implemented on October 3, 2020](https://github.com/Extended-Thunder/send-later/issues/18)). I'll get this fixed later today.

**Comment by jph-sendlater** [comment]
This issue is fixed in both the 8.9 and 9.0 branches. A new version (8.9.6) will be available via ATN (normal update process) as soon as it gets approved by the reviewers.

**Comment by reinhard512** [comment]
Thanks a lot for the quick reaction. Tested version 8.9.6 today - problem is solved.
