### ISSUE TITLE
Send Later masks Bcc addresses

### ISSUE THREAD

**Issue by vohralikp** [Extended-Thunder/send-later#374]
When I use Send Later instead of usual Send, the message copied to the Sent folder does not keep the Bcc addressees.
Is there any setting that I need to adjust to have Bcc addressees still visible in the messages in the Sent folder?

**Comment by jph-sendlater** [comment]
Is the message being delivered to the bcc addresses, or are they being dropped before the message sends?

**Comment by vohralikp** [comment]
The messages are being delivered to the Bcc addresses. 
The only questionable behavior is that when I open the messages in the Sent Items folder, the messages sent using the "Send Later" do not have the list of Bcc addresses (addressees), unlike the messages that I send using the "Send" button.
The challenge is that I need to keep track of whom I have sent the messages, including of the "Blank-Courtesy-Copy" recipients.
I have the same version of Send Later (8.9.8) installed on two computers - on the older one it works correctly (Thunderbird 78.14.0 32-bit), on the newer one (Thunderbird 91.1.0 64-bit) it masks the Bcc list.

**Comment by jph-sendlater** [comment]
I responded to this in the 'discussion' thread you opened. I'm going to close the issue, since there's nothing that I can do about it. Keep an eye on the [thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1730738) for updates on progress towards fixing this.

**Comment by vohralikp** [comment]
Thank you for your diligence and detailed clarification.
