### ISSUE TITLE
wishlist: add more shortcuts

### ISSUE THREAD

**Issue by pol-hallen** [Extended-Thunder/send-later#378]
hello, please add the way to add more shortcuts :-)
thanks

Pol

**Comment by jph-sendlater** [comment]
Can you elaborate? Why do you need more shortcuts?

Counting the actual shortcuts, plus saving a customized default schedule, plus the accelerator key preferences, there are already effectively 6 different customizable shortcuts. I don't see a compelling reason to need more. It seems like that would just clutter the UI.

**Comment by jikamens** [comment]
I agree; I think there is already enough configurability. I don't think we're going to add more.
