### ISSUE TITLE
Send Later 9.0.6 Not Functioning in Thunderbird 91.2.0

### ISSUE THREAD

**Issue by Aquaritone** [Extended-Thunder/send-later#389]
Worked fine in version 78. Since I updated to 91.2.0, there are two issues: 

1) The Send and Send Later functions of Thunderbird operate as if the "Send Later" add-on is not even installed, and no "Send Later" Dialog Box appears. Mail is sent immediately. This is regardless of which  send option is selected in the "Send Later" Options section.

2) When exiting Thunderbird and then restarting, an error dialog box appears saying that Thunderbird is still running but not responding, and you have to click the "Close Thunderbird" button to restart Thunderbird. With "Send Later" disabled, you can restart Thunderbird immediately without problem.

"Send Later" is the only Add-On I am running. The restart issue does not occur in Troubleshoot Mode, or if I manually disable "Send Later."

I updated Thunderbird to 91.2.1. and there is no change. It works once and then reverts to the above behavior permanently.

There is no game software on this computer.

**Comment by jph-sendlater** [comment]
@je-github is your comment at all related to this issue report?

@Aquaritone I had a similar report from another user recently, which was apparently resolved by completely removing the extension (as opposed tojist disabling), and then re-installing it. If that doesnt fix it, let me know and I'll get back to you with more debugging steps we can take to track it down

Just FYI, I have extremely limited time to devote to send later right now, so development and bug fixes will be very slow for the time being. I apologize in advance for the inconvenience.

**Comment by Aquaritone** [comment]
Update: None of my add-ons work. They all exhibit the same behavior as above, so it is not Send Later that is causing the problem. I reinstalled Thunderbird 91.2.1, but no improvement. I tried to revert to version 78 but got an error message that a newer version of Thunderbird (i.e. 91.2) has modified my Profile Folder and it will now not work with earlier versions of Thunderbird. So I think the issue is in my Profile Folder, which maybe has a corrupt file. 

I read that the Parent.Lock file is supposed to be deleted from the Profile Folder upon exiting Thunderbird. However in my Profile Folder, Parent.Lock remains after Thunder bird is quit. Upon advice of a troubleshooting article I deleted the Parent.Lock file and restarted Thunderbird. There was no improvement in the add-ons--they work once and then upon restarting Thunderbird, exiting results in a crash.

With all my add-ons disabled, the Parent.Lock file still remains in the Profile Folder after exiting, and as before, Thunderbird operates normally (without the add-ons) so I think the crashing is not being caused by the Parent.Lock file, however it still should be disappearing after exiting Thunderbird.

I am going to continue using Thunderbird without the add-ons. I am not going to mess around with my Profile folder since it contains all my sent and received messages since 2004.  Any ideas would be appreciated.

**Comment by jph-sendlater** [comment]
Sounds like it's probably related to [this recent Thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1732515), which seems to be befuddling the Thunderbird devs. I haven't been following that conversation closely, but it sounds like it's still an open mystery why add-ons are not working after upgrading from v78 to 91. Keep an eye on that bug, and hopefully they'll have it resolved soon.

**Comment by Aquaritone** [comment]
EUREKA! I followed the procedure outlined toward the end of the
    thread and Send Later is now working!
    
    Specifically I went to Preferences/General/Offline, and did the
    following:
    
      Unchecked "Automatically follow detected online state"
      Under "Manually state when starting up:" I clicked the button
        next to "Online"
    
    I then enabled Send Later and have tested it and closed/restarted
      Thunderbird several times and all is working normally now.
    But here's an anomaly: even though it's working, when I go back
      to the Offline settings, "Automatically follow detected online
      state" is now checked again, and there is no selection
      under "Manually state when starting up:" There are a few other
      settings that also revert back after I have changed them, most
      notable "Ask me before updating." I always goes back to
      automatically update. That said, it has always asked me first, so
      it seems like the preferences displayed are not necessarily the
      ones being followed.
    Thanks for your help!
    
    
      
        
    
    On 11/2/2021 12:36 PM, jph-sendlater
      wrote:
    
    
      
      Sounds like it's probably related to this recent Thunderbird
          bug, which seems to be befuddling the Thunderbird devs. I
        haven't been following that conversation closely, but it sounds
        like it's still an open mystery why add-ons are not working
        after upgrading from v78 to 91. Keep an eye on that bug, and
        hopefully they'll have it resolved soon.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android. 
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Extended-Thunder/send-later/issues/389#issuecomment-957926504",
"url": "https://github.com/Extended-Thunder/send-later/issues/389#issuecomment-957926504",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Aquaritone** [comment]
Fixed by Thunderbird.

**Comment by je-github** [comment]
TRIED IT - NOT FIXED

**Comment by Aquaritone** [comment]
> 

It's fixed in Thunderbird 91.3.1.

>

**Comment by je-github** [comment]
MY TB is 91 3 2 and is up to date and does not work!!
Jamie
