### ISSUE TITLE
"Send" delays messages by __ minutes option Fails Occasionally

### ISSUE THREAD

**Issue by epsso** [Extended-Thunder/send-later#390]
I am using TB 91.2.0 (64-bit) and Send Later 9.0.6 and the "Send" delays messages by __ minutes option.

Occasionally when Send Later places multiple copies of a message in the drafts folder and then hangs on the "Copy Complete" dialog box. The only way out is to close the message that you just clicked on the send button for. Then, when you click Send the messages are sent immediately instead of going though send later.

I can reproduce the issue even when Send Later is the only extension running. I can reproduce the issue when using the "Send" does "Send Later" option but not when both options are unchecked.

I have attached a copy of the web developer console. There is a "NotAllowedError: Could not remove the file at" error on line 32 that appears to be the beginning of the issue.

[Thunderbird console.txt](https://github.com/Extended-Thunder/send-later/files/7383114/Thunderbird.console.txt)

**Comment by jph-sendlater** [comment]
Sorry for the delay responding here. I just started a new job, and am swamped with that for the time being. Send later development is going to be on the back burner for a while. If you're interested in tracking this down yourself, a code patch would of course be very appreciated. Otherwise I'll get to this as soon as I have time.

**Comment by jph-sendlater** [comment]
I updated a lot of the logic related to saving messages in the latest beta version (9.2.2). Once that version gets promoted to stable (next week or two) please check again and let me know if this is still an issue. Until then I'm going to close this ticket.
