### ISSUE TITLE
False "corrupted drafts folder" error after sending past-due emails

### ISSUE THREAD

**Issue by tomatic** [Extended-Thunder/send-later#395]
### Summary ###

I some instances my Thunderbird isn't running when a message is set to be sent by Send Later. So when I eventually launch TB again, Send Later checks the drafts folder for pending emails. If there's an email sitting in there whose send time has passed, it sends it out but doesn't delete it from the drafts folder afterwards. Then when Send Later checks the drafts folder for pending emails the next time, it throws the "corrupted drafts folder" error, stating that there's an email in drafts that has already been sent. So it seems that Send Later is firing the wrong error in this scenario.

### Steps to reproduce ###

1) Schedule an email to be sent a couple of minutes in the future.
2) Close Thunderbird and leave it closed until the send later time for that email has passed.
3) Re-open Thunderbird.

### Expected result ###

Email gets sent and then deleted from drafts folder.

### Actual result ###

Email gets sent, but **not** deleted from the drafts folder. It initially seems like it's gone from drafts, but re-appears after it's sent. On the next check of the drafts folder, Send Later throws the "corrupted drafts folder" error because there's an email in drafts that it knows has already been sent but that thererfore should not be there anymore.

Apart from this, Send Later generally works without issue for me, i. e. it sends out emails as scheduled and has no problems deleting them afterwards from drafts. The issue only happens with past-due emails that get sent out after TB is launched.

### System info ###

- Thunderbird 78.11.0 (64-bit) on Kubuntu 21.04.
- Send Later 8.9.8 from Sept 8, 2021

**Comment by jikamens** [comment]
I haven't seen this issue. :thinking:
Does this issue still occur with current Thunderbird (not TB115, though, since Send Later isn't supported there yet!) and Send Later?
If so, is it reproducible for you?
If so, can you tell me what your mail server is (e.g., Gmail, Hotmail, etc.)?
Also, do you have TB configured to save copies of sent messages in a folder?

**Comment by tomatic** [comment]
I just tried it with the current stable Thunderbird 102.13.0 and Send Later 9.2.9 and the issue didn't occur anymore. Seems it got solved with one of the updates since 2021 😉
