### ISSUE TITLE
Auto-save drafts not working... Extension related?

### ISSUE THREAD

**Issue by truthsword** [Extended-Thunder/send-later#397]
In the middle of composing a long message, a pop-up says that the draft was unable to be saved, so it offered to save it in a Local Folders' sub-folder. Why?

Later, I used the extension "Save Later" and the delayed message ended up in the proper Drafts folder.

Why don't regular drafts auto-save to the Drafts folder? Is the "Save Later" extension preventing draft auto-saves from working?

v91.3 Windows 10

**Comment by jph-sendlater** [comment]
Send Later does use the same internal function for saving drafts that the auto-save uses, so it's surprising that one would work and not the other. I can't totally rule that out as a possibility, but I don't see any way that Send Later could be the cause of the auto-save issue.

Does it work to manually save, using `ctrl+s`?

**Comment by truthsword** [comment]
> Does it work to manually save, using `ctrl+s?`

Yes. I have temporarily disabled the extension. Have seen no issues since, but have written few messages. Too early to tell. Drafts are saves to mail provider's drafts folder (not “drafts” on local folders).

**Comment by jph-sendlater** [comment]
I'm going to assume this is resolved? Let me know if not and I can reopen the issue.
