### ISSUE TITLE
Send later seems to hang when inputting full date

### ISSUE THREAD

**Issue by sukiletxe** [Extended-Thunder/send-later#398]
I am using Thunderbird 91.3.0 in Windows 10 64 bit, and send later version 9.0.6. If I use the date and time pickers all works fine, but if I try to enter a full date (year and all) in the edit field, thunderbird freezes when I enter the second number of the year (so if I try 15/11/2021, it will freeze when entering the 0). I have to go out and in the window again. In the process the send later dialog closes.

(Now I know the year is not necessary and I don't enter it anymore, but I report this because I think it's an important bug).

**Comment by jph-sendlater** [comment]
Thanks. This might be related to #401 . I'll look into it as soon as I have a chance.

**Comment by jph-sendlater** [comment]
Following up on this, check out the discussion on #409 . Does that solution also fix this issue by any chance?

**Comment by jph-sendlater** [comment]
The custom formats need to be specified using one of the standard date format types (e.g. `%H:%M` formats as hours:minutes). See here for references: https://sugarjs.com/dates/#/Formatting
