### ISSUE TITLE
between column on the left side cannot be deleted

### ISSUE THREAD

**Issue by dtantono** [Extended-Thunder/send-later#404]
Hi
I have Thunderbird 78.13 in Ubuntu 20.04.3 and Thunderbird 91.3 in Windows 10 that displayed the same problem. The issue is when I want to delete the between column by right click the between column or try to conceal it by dragged it the far left. The "between" column is not disappeared after I try to reboot my PC and delete the addon
<img width="140" alt="Screenshot 2021-11-15 174825" src="https://user-images.githubusercontent.com/29157187/141781496-2f3c72df-1b05-4fb8-80fa-443f522764a9.png">

**Comment by jph-sendlater** [comment]
I don't know what the between column is. Do you have another extension that creates the "between" column?

**Comment by dtantono** [comment]
the reason I asked that because mozilla thundebird team points that the problem lies to your extension (https://bugzilla.mozilla.org/show_bug.cgi?id=1741137).

**Comment by jph-sendlater** [comment]
Do you have other extensions installed? I've never heard of the 'between' column.

**Comment by dtantono** [comment]
Hi 
it looks like this problem related to the addon called thunderbird conversations and after I deleted this addon. the problem is gone.
