### ISSUE TITLE
Datestring format mismatch between Send at and the date picker

### ISSUE THREAD

**Issue by lkarabeg** [Extended-Thunder/send-later#409]
Steps to reproduce:

1. Open the Send Later dialog
2. Press Tab to go from Send At to the date picker (the Send at field will update)
3. Press Shift + Tab to go back to Send at (the datepicker will now update with a new date)

![image](https://user-images.githubusercontent.com/23399564/145458064-0ac4b861-910b-490a-b7ba-f7b1c136b493.png)
![image](https://user-images.githubusercontent.com/23399564/145458110-99f4fa3f-1eeb-4db1-8c36-ff3829948a8c.png)
![image](https://user-images.githubusercontent.com/23399564/145460203-7afec2ec-caed-47db-9411-34b0ec64a08b.png)

What appears to be happening is that the date picker is providing a little-endian date, like dd.MM.yyyy which is being misinterpreted as a middle-endian date, like M.dd.yyyy. 

Another way to demonstrate the problem is to select a date and click the "Save these values as the defaults" button. After closing and reopening the dialog, the wrong date will be set as default.

I'm running Windows, and my system date format is yyyy-MM-dd. My more general format preference is set to "Norwegian bokmål", which I would guess might be determining the date picker format. 

I've used Send later for a very long time, and the problem just appearred recently, so I suspect it's a regression in version 9.06.

**Comment by lkarabeg** [comment]
I may have accidentally duplicated #401, but I'll leave this here as it's a bit better explained IMO.

**Comment by lkarabeg** [comment]
The problem goes away when I set a custom short date format in the options. Now saving defaults works, and the date picker and Send at field agree after the dates have been reinterpreted as shown above.

**Comment by jph-sendlater** [comment]
Date-time parsing/formatting has always been an issue. It seems like fixing one inconsistent behavior always somehow breaks another one :roll_eyes:. Anyway, I'm glad the custom date/time format feature seems to be working for you. Let me know if you run into any more issues.
