### ISSUE TITLE
Send Later 9.0.6 Not Functioning in Thunderbird 91.4.0 - Encryption??

### ISSUE THREAD

**Issue by DieterBub** [Extended-Thunder/send-later#410]
Macbook Pro, OS Big Sur - 11.6
Thunderbird 91.4.0, auto-update enabled
Send Later 9.0.6

I have been using Send Later for several months without issue.
Recently, I enabled encryption and draft emails are no longer being sent by Send Later. If I disable encryption, Send Later works as expected. 

I am happy to collect any information or logs you think would be helpful.

**Comment by jph-sendlater** [comment]
Unfortunately there are still changes on Thunderbird's side that prevent Send Later from being compatible with the new PGP system. See here for details: #200
