### ISSUE TITLE
v9.0.8 does not work

### ISSUE THREAD

**Issue by Feri-6** [Extended-Thunder/send-later#411]
The latest 9.0.8 version does not work. It does not send the e-mails at the set date. Previous version worked well.

TB 91.4 64bit, Win 10

**Comment by Bluestone357** [comment]
Same here.
          TB 91.4  32 bit Win 10
          How do I revert? sdjkg   dgsfh   the spellchecker doesn't
          kjsafh  dasgsdgh  fh  sdgfhgj  k 
          
          Kind regards,
          
          Paul 
          Sent using 100% recycled electrons
        
      
    
    On 20/12/2021 11:31, Feri-6 wrote:
    
    
    The latest 9.0.8 version does not work. It does not
      send the e-mails at the set date. Previous version worked well.
    TB 91.4 64bit, Win 10
    —
      Reply to this email directly, view it on GitHub, or unsubscribe.
      Triage notifications on the go with GitHub Mobile for iOS or Android.
      
      You are receiving this because you are subscribed to this thread.Message
        ID: ***@***.***>
    [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Extended-Thunder/send-later/issues/411",
"url": "https://github.com/Extended-Thunder/send-later/issues/411",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by beebmaster** [comment]
Same for me in Thunderbird 91.3.2 (64-bit) on Ubuntu 20.04, messages just stay in drafts forever.  I reverted to 9.0.6 and it's back to working again.

**Comment by jph-sendlater** [comment]
Sorry everyone! The patch I introduced to fix an issue in TB beta yesterday also introduced the same issue in TB ESR. I submitted a patch for it (9.0.9), which will be available as soon as it gets approved by the TB developers.
