### ISSUE TITLE
Pop-up calendar not working

### ISSUE THREAD

**Issue by swcalif** [Extended-Thunder/send-later#418]
I've been using Send Later for several years. I noticed today that when clicking on the date, the calendar pop-up does not display. However, I can still enter the date manually.

My OS is Windows 10 Pro Version 21H1 Build 19043.1466, Thunderbird version is 91.5.0 (32 bit) and the Send Later version is 9.0.9 dated 12/21/21

Thank you.

**Comment by Bluestone357** [comment]
Me too.Sent using 100% recycled electrons.T10
-------- Original message --------From: swcalif ***@***.***> Date: 18/01/2022  22:51  (GMT+00:00) To: Extended-Thunder/send-later ***@***.***> Cc: Subscribed ***@***.***> Subject: [Extended-Thunder/send-later] Pop-up calendar not working (Issue #418) 
I've been using Send Later for several years. I noticed today that when clicking on the date, the calendar pop-up does not display. However, I can still enter the date manually.
My OS is Windows 10 Pro Version 21H1 Build 19043.1466, Thunderbird version is 91.5.0 (32 bit) and the Send Later version is 9.0.9 dated 12/21/21
Thank you.

**Comment by jph-sendlater** [comment]
These sorts of UI issues are outside of what extensions can control. If you're still having this issue, you'll have to file a bug against Thunderbird itself.
