### ISSUE TITLE
SendLater placing emails in Outbox but not sending

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#419]
Since the last Thunderbird update, if I press "send in 5 minutes", the message is transferred to Drafts, then after 5 minutes it goes to Outbox and just sits there.
If I press Send now, it goes straightaway with no issues.

Sendlater version 9.0.9
Thunderbird version 91.5.0

Am just about to update to tbird version 91.5.1
Have done so and it seems that this latest tbird update has fixed the issue.

**Comment by jph-sendlater** [comment]
Am I understanding correctly that this issue is fixed with Thunderbird 91.5.1? If so, is it okay for me to close this issue?

**Comment by tplanter** [comment]
Yes, please close. Thunderbird 91.5.1 has fixed the issue.
Thanks
