### ISSUE TITLE
The popup Calendar is hidden behind the main dialog.

### ISSUE THREAD

**Issue by Nicolian** [Extended-Thunder/send-later#420]
Thunderbird 91.5.1
Send Later 9.09
Windows 10 Pro 21H2

Just installed TB and Send Later on a new computer and when scheduling an email, the pop-up calendar is at the back of the dialog box and we can't pick a date. I can only see the bottom of the calendar, so we have to enter the date manually. 
It should be an easy fix to bring the pop-up calendar to the front....?

Thanks.

**Comment by Bluestone357** [comment]
Me too.
      Had TB for years - regularly updated.
    
    
      
      
      
          
          Kind regards,
          
          Paul 
          Sent using 100% recycled electrons
        
      
    
    On 01/02/2022 02:41, Nicolian wrote:
    
    
      
      Thunderbird 91.5.1
        Send Later 9.09
        Windows 10 Pro 21H2
      Just installed TB and Send Later on a new computer
        and when scheduling an email, the pop-up calendar is at the back
        of the dialog box and we can't pick a date. I can only see the
        bottom of the calendar, so we have to enter the date manually.
        It should be an easy fix to bring the pop-up calendar to the
        front....?
      Thanks.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Extended-Thunder/send-later/issues/420",
"url": "https://github.com/Extended-Thunder/send-later/issues/420",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jph-sendlater** [comment]
Sorry, but these sorts of UI issues are outside of the scope of what extensions can control. You'll need to file a bug against Thunderbird itself.
