### ISSUE TITLE
Calendar hides behind option screen

### ISSUE THREAD

**Issue by truthsword** [Extended-Thunder/send-later#422]
I'm using Thunderbird 91.5.1 and Send Later 9.0.9. When I select the date field to schedule a message, the calendar window is hidden behind the main screen:

![](https://i.imgur.com/UAlhVGD.png)

**Comment by jph-sendlater** [comment]
This is a bug in Thunderbird. Extensions don't handle rendering the GUI. I'm pretty sure the Thunderbird developers are aware of this, and it might already be fixed in 91.5.3 (but I'm not positive about that)
