### ISSUE TITLE
Seems Send Later and PGP encrypting drafts does not play nice

### ISSUE THREAD

**Issue by Oclair** [Extended-Thunder/send-later#427]
Hi there,
I recently tried to use the plugin but noticed that the message never got sent, and rather odd was preventing thunderbird from quitting.

I noticed that the send later mail were considered drafts and then saw an error pop up about encryption and that the send later command was not processed due to the drafts being encrypted by some setting related to my pgp keys.

Anyways as pgp is now handled in thunderbird it's self I would like to ask if Send Later has been checked out with how drafts can be encrypted on the server?

Thank you for the awesome feature and support to the community,
Have a great day everyone!
Oclair

**Comment by jph-sendlater** [comment]
PGP compatibility is being tracked/discussed in #200

**Comment by jikamens** [comment]
The current version of TB allows you to disable encryption of drafts for a particular email account, so you can use Send Later with it. See the "Store draft messages in encrypted format" checkbox on the "End-To-End Encryption" page of the account settings. If you disable this checkbox for an account then you are able to use Send Later with that account.
