### ISSUE TITLE
does not send on ubuntu

### ISSUE THREAD

**Issue by bruvio** [Extended-Thunder/send-later#437]
messages are not sent in ubuntu 20.04 using thunderbird 91.7.0 64bit

messages go into the account's draft folder and stay there. the column with "send later" time shows up.

tried also to switch to local folder's draft folder for storage of drafted messages with no luck.

**Comment by jph-sendlater** [comment]
Please work through these troubleshooting steps and let me know what you find: https://extended-thunder.github.io/send-later/#troubleshooting

**Comment by ashkanr65** [comment]
I tried all of the solutions here:
https://extended-thunder.github.io/send-later/#troubleshooting
But still have problem.
It says that it failed to put email to outbox. I cked all steps but still...
My ubunutu is 20.04.4 and my thunderbird is 91.9.1 (64-bit)

**Comment by jikamens** [comment]
@ashkanr65 still having this issue? If so can you please post a screenshot of the error you are getting?

Also, can you confirm that when you view "All folders" in the folder list, you have a "Local Folders" virtual account listed there and an "Outbox" folder within that virtual account?

If so, can you please confirm that you are able to copy a message into that "Outbox" folder successfully using drag-and-drop within TB, totally separate from Send Later (after performing this test please make sure to remove the message from the folder or it will get treated as an unsent message and sent by TB later, which you probably don't want)?

**Comment by jikamens** [comment]
If you've confirmed all of the above and Send Later still isn't sending scheduled messages, and you have more than 100 messages in your Drafts folder, then you are probably running into the bug described in #529, which will be fixed in the next Send Later release.
