### ISSUE TITLE
Option to not see the Send Later dialog upon exit of Thunderbird?

### ISSUE THREAD

**Issue by telrod11** [Extended-Thunder/send-later#440]
Firstly, thanks for "Send Later"!

Could we get the option of not seeing:
"Send Later can only send messages when Send Later is running. Please remember to restart it before your messages are scheduled to be sent!"
upon exiting TB?

Thanks

**Comment by jph-sendlater** [comment]
The preference "`Show warning before quit if there are pending messages`" is what you're looking for. It should show up in the add-on preferences page. Let me know if it isn't working.

**Comment by telrod11** [comment]
Thank you!!  Sorry, totally missed that!
