### ISSUE TITLE
No "Option" tab, no pop up diaolog when "Send later"

### ISSUE THREAD

**Issue by rndvip** [Extended-Thunder/send-later#441]
Windows 10 Pro, Thunderbird 91.09.0, Send later 9.0.10, without Internet connection.
In Thunderbird plugin settings, no tab "Option" on "Send later" plugin. Only "Details" and "Permissions".
When "Send late" - popup dialog not showing.

**Comment by sebastienserre** [comment]
Hello,

Same problem here (Ubuntu 22.04 - TB 91.9.1 - Send Later 9.0.10

**Comment by jph-sendlater** [comment]
That would be a Thunderbird issue, not a Send Later one. As @sebastienserre mentioned, the solution would usually be to restart Thunderbird and/or re-install the add-on.
