### ISSUE TITLE
set different locale (mm/dd/year) --> (dd/mm/year)

### ISSUE THREAD

**Issue by pol-hallen** [Extended-Thunder/send-later#444]
Hello, also change date format (like screenshot1) on the main windows I always see (screenshot2) date format as mm/dd/year I use english language but I'd like have this locale: dd/mm/year
thanks for help :-)

![screenshot1](https://user-images.githubusercontent.com/67121219/171184817-7edd080b-e74c-4a91-bbce-fcc387449b87.png)
![screenshot2](https://user-images.githubusercontent.com/67121219/171184819-3ef0a364-76db-4378-9194-2a86d5f9c61d.png)

**Comment by jph-sendlater** [comment]
You need to specify a date *format*, not just type a date into those fields. In your case, it would be `%d/%m/%Y, %H:%M`

**Comment by pol-hallen** [comment]
Also fill with these: %d/%m/%Y, %H:%M I've same results :-/ I removed and reinstalled extension but same problem. It happens only with this pc, other works.

Is there any files can I will remove? Maybe sendlater read a wrong config file :-/ 
can you help me? thanks
Pol

{
  "checkTimePref": 1,
  "checkTimePref_isMilliseconds": false,
  "quickOptions1Label": "15 minutes from now",
  "quickOptions1funcselect": "Delay",
  "quickOptions1Args": "15",
  "quickOptions2Label": "30 minutes from now",
  "quickOptions2funcselect": "Delay",
  "quickOptions2Args": "30",
  "quickOptions3Label": "2 hours from now",
  "quickOptions3funcselect": "Delay",
  "quickOptions3Args": "120",
  "accelCtrlfuncselect": "Delay",
  "accelCtrlArgs": "5",
  "accelShiftfuncselect": "BusinessHours",
  "accelShiftArgs": "",
  "showHeader": true,
  "showColumn": true,
  "showStatus": true,
  "logConsoleLevel": "info",
  "logDumpLevel": "fatal",
  "logFilter": "",
  "sendUnsentMsgs": true,
  "sendDrafts": true,
  "sendButton": false,
  "sendDoesDelay": false,
  "sendDelay": 10,
  "sendDoesSL": false,
  "showEditAlert": true,
  "showOutboxAlert": true,
  "showSendNowAlert": true,
  "altBinding": false,
  "sendWhileOffline": true,
  "enforceTimeRestrictions": true,
  "blockLateMessages": true,
  "lateGracePeriod": 2880,
  "activeScanner_lastUUID": "{d4f8bfed-33f8-487d-b649-a9c77c118ea1}",
  "activeScanner_UUID": "",
  "activeScanner_time": 1569999627,
  "askTime": 0,
  "askSent": 0,
  "askQuit": true,
  "relNotes": "6.4.6",
  "disabledForEnigmail": false,
  "editorFirstUse": false,
  "promptDefaults": "",
  "markDraftsRead": true,
  "composeWindowHotkeys": true,
  "instanceUUID": "{6128dc74-5ee0-4c40-8fbb-09f1b21d5a17}",
  "throttleDelay": 0,
  "customizeDateTime": true,
  "shortDateTimeFormat": "%d/%m/%Y, %H:%M",
  "longDateTimeFormat": "%d/%m/%Y, %H:%M",
  "migratedLegacy": 7
}
