### ISSUE TITLE
Send Later column keeps reappearing on Inbox when Thunderbird launches 

### ISSUE THREAD

**Issue by ToddDTaft** [Extended-Thunder/send-later#448]
I did a fresh install of Thunderbird 102 on macOS 12.4 and installed Send Later 9.0.11.

Frequently, when launching Thunderbird, the Send Later column will appear in the message listing of my default account's Inbox.

Even if I manually remove the column, it will often re-appear the next time I start the program.

This appears to happen most frequently when Thunderbird takes a long time contacting servers for updates at launch (e.g. slow network).

**Comment by SGKrueger** [comment]
I've also noticed this issue related to the latest version 102.  I've got some other extensions that were completely disabled by this upgrade and some of my folders are no longer accessible.

**Comment by merlin555** [comment]
I have the same problem on Windows 10 21H2, with v102.0.3. (Send Later v9.0.11)

Every time I restart Thunderbird, the "Send Later" box appears next to "Inbox" and "Drafts".
Cannot be deleted.

**Comment by siffegh** [comment]
Reddit user complaint: https://www.reddit.com/r/Thunderbird/comments/w5e264/inbox_keeps_displaying_a_column_that_i_hide_every/.

**Comment by cooch17** [comment]
Same for me - TB 102.1.2 (64-bit) - Win 10 Pro -- doesn't matter if you try to turn off the column by customizing the TBird inbox, or if you uncheck the box in the SendLater options.  This is also worth noting. If you 'turn off the column', shut down TBird, then re-start it, the Send Later column is not shown initially, but 2-4 seconds later, shows up again (a delayed write to the screen).

**Comment by cooch17** [comment]
Possibly important 'clue' -- I just tried a 'fresh install' of TB102.x.x into a Win 10 virtual machine -- and the problem (as described, above) doesn't occur. For amusement, IU uninstalled TNB102, did a fresh install of 91.x.x, then tried an inplace upgrade from 91 -> 102, and problem emerged. So, the 'problem' might be some weird artifact on inplace updates to TB91 (either to TB itself, or to SendLater).

**Comment by cooch17** [comment]
Confirmed. The TB install I have in one of my VMs just updated to 102.2. In the process of in-place updating, the 'Send later' columns no reappear in the inbox. I'll try uninstalling TB and do a clean TB 202.2 install to see. My gut tells me the issue has something funky to do with in-place updates breaking something.

**Comment by tanfwc** [comment]
+1

Facing the same issue on TB 102.2.0 and Win 10. Upgraded TB and face this issue

**Comment by cooch17** [comment]
I just did a clean install of Win 11 in a virtual machine (once I figured out how to hack the registry to bypass TPM requirements ;-(

At any rate - will try a TB 102.2.2 install, and SendLater as only addon. Stay tuned.

**Comment by taylormia** [comment]
Same problem here. The Send Later column keeps re-appearing at every startup of TB 102.2.2. Does not matter whether it is a fresh istall of TB or an in-place upgrade. Please fix. Thanks.

**Comment by ehws** [comment]
Same here - happens even on a fresh install on Win 8.1!

**Comment by jikamens** [comment]
I'm also seeing this.

**Comment by jph-sendlater** [comment]
:+1: I'm on it. Sorry for the delay getting to this- I've had a very busy summer, but I will have time for sendlater more in the coming weeks and months. Stay tuned.

**Comment by hellyguo** [comment]
#467 duplicate with this issue. I also wait a solution.

**Comment by jph-sendlater** [comment]
I finally had a whole long weekend to work on SendLater. I made a lot of progress on other tasks, but this one is still eluding me. I can't reproduce it locally, and I've combed through the code for the column element several times but haven't found any obvious problems. I did change lots of things in the latest beta that might affect this, so hold tight until v9.2 is released and let me know if the problems persist.

**Comment by hellyguo** [comment]
I updated to v9.2.2 pre-release version. It works well. Thanks. @jph-sendlater

**Comment by joeyconnick** [comment]
9.2.2 fixed it for me, on macOS Monterey 12.6.1 👍

**Comment by uwe-ss** [comment]
9.2.2 fixed it for me, too. on Ubuntu 20.04 & Betterbird

**Comment by merlin555** [comment]
Finally it works.
Thanks !

**Comment by tanfwc** [comment]
Fixed for me as well 👍 

9.2.2
TB 102.5.0
Windows 10

**Comment by ehws** [comment]
When will 9.2.2 be available for update/download?

**Comment by jikamens** [comment]
> When will 9.2.2 be available for update/download?

https://github.com/Extended-Thunder/send-later/releases/tag/9.2.4_1

**Comment by ehws** [comment]
Tnx

**Comment by ehws** [comment]
Tried V9.2.4 with TB102.5 - fixes the problem, but it feels like it's slowing TB down - often at 100% CPU...

Any ideas?

**Comment by jph-sendlater** [comment]
@ehws Probably the same as #497. I'm hoping that one is solved in the upcoming release.

**Comment by ehws** [comment]
Went back to 9.1.1 - speed back to normal.

Will try newer versions...
