### ISSUE TITLE
Mail server responds "mail size of zero not allowed" when Send Later tries to send

### ISSUE THREAD

**Issue by hseliger** [Extended-Thunder/send-later#449]
Hi!
Using Send Later version 9.0.11 on Fedora/Wayland with Thunderbird 102.0 64-bit.

When using Send Later, the messages stays in Drafts until the time it is supposed to wait expires, then Thunderbird tries to send it. At that point I get an alert (see [Screenshot](http://pub.hseliger.eu/SendLaterProblem-220706.png) ) that the server rejects the message because "mail size of zero not allowed".

This occurs using different accounts with different SMTP servers, and sending does work without issues when Send Later is disabled.

BTW, the message seems to end in the outbox, but if I try to open it there, I just see Thunderbird "Loading…" to no avail, no mesage comes, although the size is indicated (for my last test message it shows 1.6kB, so definitely not zero).

Any ideas how to solve? Thanks!!

**Comment by jikamens** [comment]
@hseliger are you still having this issue? If so, it sounds like your Outbox may be corrupt. Please follow [these instructions](https://extended-thunder.github.io/send-later/#corrupt-outbox-folder) for repairing it. After doing that, also try this test:

1. Disable the Send Later add-on.
2. Quit and restart TB.
3. Compose a draft message to yourself.
4. Select the File > Send Later menu command in the compose window.
5. Confirm that the message is deposited by Thunderbird into the Outbox folder under Local Folders.
6. Select File > Send Unsent Messages and confirm that the message is successfully delivered to you.

If all that works properly then turn Send Later back on and quick and restart Thunderbird and see if Send Later starts working again.

**Comment by hseliger** [comment]
Thanks for the follow-up. Seems to work now!
