### ISSUE TITLE
Column order and sort settings do not persist across restart

### ISSUE THREAD

**Issue by jperryhouts** [Extended-Thunder/send-later#45]
If you rearrange columns in the drafts folder, or choose to sort messages by their schedule time, those settings may not persist across restarts.

**Comment by rgrun1** [comment]
Even the new SendLater column does not persist. If you invoke it, the times do not populate unless you open a message in the drafts folder and then close it

**Comment by jperryhouts** [comment]
This is really annoying, but the Drafts folder column will not sort in the new version no matter what I do. I have no idea why. It's not a huge deal, but it's definitely irritating. This is low priority for me, but it's still on my radar.

**Comment by jperryhouts** [comment]
Column sorting is fixed by #86 and I *think* the sort settings should persist, but I'm always running in debug mode so nothing persists for me anyway. Someone else will have to let me know if that still does not work. Until then I'm going to (optimistically) mark this issue as closed, and hope it can stay that way :)

**Comment by rgrun1** [comment]
It is fixed here so thanks!

**Comment by jperryhouts** [comment]
Glad to hear it!
