### ISSUE TITLE
only first message of recurring is sent

### ISSUE THREAD

**Issue by j47996** [Extended-Thunder/send-later#456]
fedora 36
tbird 91.12.0
send later 9.0.11

Account set to non-encrypted draft messages.

Set up a message with "5 min from now" and "every day".  The first one goes, but the message from the Drafts
folder is removed and not replaced at that time.  There is a pop-up indicating an IMAP problem.

Debug--level console snippet:

Object { _sendUnsentMsgs: true, localFile: XPCWrappedNative_NoHelper }
sl3u.js:27
WebExtensions: DEBUG [SL3U]: SL3U.sendRaw.CopyUnsentListener.OnStopCopy: Successfully copied message to outbox. sl3u.js:27
WebExtensions: DEBUG [SL3U]: SL3U.sendRaw.CopyUnsentListener.OnStopCopy: Triggering send unsent messages. sl3u.js:27
Scheduling next recurrence of message <ccde5480-8c72-96b1-d90a-f596121a3e6c@wizmail.org>
Object { nextRecurAt: Date Mon Aug 15 2022 14:35:00 GMT+0100 (British Summer Time), nextRecurSpec: undefined, nextRecurArgs: undefined }
background.js:583:18
Locked message <<ccde5480-8c72-96b1-d90a-f596121a3e6c@wizmail.org>> from re-sending. background.js:551:20
WebExtensions: DEBUG [SL3U]: SendLaterFunctions.copyStringMessageToFolder Saving message to /tmp/tempMsg3.eml sl3u.js:27
Messages received in folder /INBOX/mailinglists/ietf/tls background.js:1546:14
Scheduled next occurrence of message <<ccde5480-8c72-96b1-d90a-f596121a3e6c@wizmail.org>>. Deleting original. background.js:649:20
WebExtensions: DEBUG [SL3U]: Deleting message (imap-message://jgh%40wizmail.org@wizmail.org/INBOX/Drafts#3238) sl3u.js:27
WebExtensions: ERROR [SL3U]: SL3U.saveMessage: 0x80550021 sl3u.js:27

[next log line is dealing with a different account]

**Comment by jph-sendlater** [comment]
Looks like there's an IMAP failure when creating the newly scheduled message. The underlying cause is outside of my control, but I'll look into ways to make SendLater more robust to that kind of issue.

**Comment by jikamens** [comment]
@j47996 are you still seeing this issue? What kind of IMAP server is TB talking to when this issue occurs?

**Comment by jikamens** [comment]
Closing because no response from original reporter and not reproducible. Please reopen or comment if you're still seeing it.
