### ISSUE TITLE
Date picker window displays behind the Send Later window

### ISSUE THREAD

**Issue by OsadaP** [Extended-Thunder/send-later#458]
Windows 10
Thunderbird 102.1.2
Send Later 9.1.1

When selecting 'send at' date ('Wyślij o' at picture) from calendar then date picker window (red frame) appears under the Send Later window (green).

And using calendar of 'until' date (blue) shows on top only part of it that is not covered by Send Later window.

![Send Later](https://user-images.githubusercontent.com/86242069/186744558-407f426b-fdad-416c-b4b6-0932a8e40635.png)

**Comment by OsadaP** [comment]
This screen shot is from Linux, where calendar rendering behaves correctly.

**Comment by jph-sendlater** [comment]
Rendering issues are problems in Thunderbird (probably inherited from Firefox). I've heard about this specific issue before, but I don't know what the status is. In any case, you should check the Thunderbird and/or Firefox bug trackers for this one. There's unfortunately nothing I can do on the extension side to fix it.

**Comment by OsadaP** [comment]
Thunderbird bug 1 791 537:
https://bugzilla.mozilla.org/show_bug.cgi?id=1791537

**Comment by OsadaP** [comment]
So I have reported this bug in Thunderbird bug tracker and Magnus Melin claims that it is add-on problem:

"Please report it to the Send Later author. Add-on issues are not tracked in bugzilla".
https://bugzilla.mozilla.org/show_bug.cgi?id=1791537#c2

**Comment by jobisoft** [comment]
I will have a look at the created bug. I am also 99% sure it is a Thunderbird issue.

**Comment by OsadaP** [comment]
It is fixed in TB 102.5.1.
https://bugzilla.mozilla.org/show_bug.cgi?id=1791537#c12

**Comment by Maxsurfer** [comment]
After 7 months it works again. Unbelievable.
