### ISSUE TITLE
Wrong date/time format in 'Send Later' column

### ISSUE THREAD

**Issue by ehws** [Extended-Thunder/send-later#459]
My MS Windows is set to the Australian locale and therefore displays the 24h date/time format e.g. 16/09/2022 23:44, 19/09/2022 07:30, etc.

When I set a Send Later item, the date in the Drafts column has the wrong format of **19/09/2022 7:30 am** (instead of 19/09/2022 07:30 as per the MS Windows systems setting)

![SendLater Date Bug](https://user-images.githubusercontent.com/4878970/190856388-abafea4e-0cda-4fe3-9039-8dbe09280e4a.png)

Love SendLater, please have a look at this. Thank You.

**Comment by jcmuaz** [comment]
I've set mine up in non-US format, even though my computer is using US settings. Maybe this will help:
![send_later_date](https://user-images.githubusercontent.com/47476049/190919444-f60d15c8-6e99-4743-873c-46829440d465.jpg)

**Comment by jcmuaz** [comment]
More info on time/date format here:
https://sugarjs.com/dates/#/Parsing

**Comment by ehws** [comment]
Thanks @jcmuaz - that (eg {d}/{MM}/{yyyy}, {HH}:{mm}) helped fix the immediate problem.  The maintainers might add the sugerjs link next to the option?

The real question is why SendLater doe snot seem to inherit the locale from TB?

**Comment by jph-sendlater** [comment]
> The maintainers might add the sugerjs link next to the option?

Noted

> The real question is why SendLater does not seem to inherit the locale from TB?

That is the question indeed. It's surprisingly tricky for no obvious reason, but that's why the "customize date/time formats" option exists in the first place.
