### ISSUE TITLE
Alt-N accelerator key to send message now does not work

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#462]
Thunderbird 102.3.0, Ubuntu 22.10 (kinetic), "Send does Send Later" is set, I type Ctrl-Enter, to send a message, it pops up the Send Later dialog, I type Alt-N to use the "Send Now" accelerator, nothing happens.

**Comment by jph-sendlater** [comment]
I think the default behavior is that the accelerator keys are mapped to `Alt`+`Shift`+`*`. It's handled on the Thunderbird side via the html element's `accessKey` property.

**Comment by jph-sendlater** [comment]
:+1: I'll look into how the access keys work when I get a chance.
