### ISSUE TITLE
TB 102.3.1, Send Later header field is not populated in message view

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#464]
Message view:

![image](https://user-images.githubusercontent.com/1598067/194107452-9f248828-25be-48d9-aafc-0fc377be303d.png)

**Comment by geg-ck** [comment]
I see this problem too. Additionally, in the debug logs it says no email in my Draft folder has an x-send-later header and emails do not send later. If I have the Send Later column turned on it will show a future date/time for emails triggered to Send Later. However, at the scheduled date/time the column data erases.

**Comment by jph-sendlater** [comment]
Fixed in latest beta (9.2.1)
