### ISSUE TITLE
Invisible Field Text

### ISSUE THREAD

**Issue by atscomms** [Extended-Thunder/send-later#466]
Send Later window opens with no text next to fields or buttons, at least in Dark Mode
Send Later V 9.0.11
TBird V 102.3.3 (32-bit)
![Capture](https://user-images.githubusercontent.com/60936473/196075954-f72bf96c-5a43-4cd5-953d-afc3fbf8b32c.JPG)

**Comment by jph-sendlater** [comment]
This is a known Thunderbird/Firefox issue. I don't know the status of it on their end, but I might have found a workaround for it that's included in the next send later release (9.2.1; currently in beta).
