### ISSUE TITLE
Option: "Show Send Later Column" does not take effect after setting

### ISSUE THREAD

**Issue by hellyguo** [Extended-Thunder/send-later#467]
I have set "Send Last Column" to false.
![Screenshot from 2022-10-21 11-24-56](https://user-images.githubusercontent.com/1480942/197105462-0fba65f8-9e56-4223-9c49-bb460a7de657.png)

However, it still appears after Thunderbird is restarted.
![Screenshot from 2022-10-21 11-25-54](https://user-images.githubusercontent.com/1480942/197105470-7c939658-2502-4833-96d1-f1ccf0b7cb63.png)

Can anyone fix this? Thanks!

**Comment by tomatic** [comment]
Same for me, but if you select a different folder and then go back to Inbox, the column is gone.

**Comment by tomatic** [comment]
Possible duplicate of [#448](https://github.com/Extended-Thunder/send-later/issues/448)

**Comment by hellyguo** [comment]
Yes, this is a duplicate of #448. Close it.
