### ISSUE TITLE
Encryption compatibility issue

### ISSUE THREAD

**Issue by eastbaytech** [Extended-Thunder/send-later#468]
Messages that are copied to drafts using the send later plugin say "Encryption compatibility issue" and ultimately never get sent.

<img width="472" alt="Screen Shot 2022-10-25 at 11 05 54 AM" src="https://user-images.githubusercontent.com/5571323/197849300-47f75c70-89df-4bbf-962f-f53411df96ba.png">

**Comment by jph-sendlater** [comment]
See #200

**Comment by eastbaytech** [comment]
I do not believe this is related to issue 200 as I do not use mail encryption/pgp. The message that is sitting in drafts marked for send later is not encrypted when showing the error I sent. Please re-open my issue. On Nov 13, 2022, at 1:27 PM, jph-sendlater ***@***.***> wrote:﻿
See #200

**Comment by jph-sendlater** [comment]
Have you setup encryption in the past? If so, it's likely that regardless of whether you intended to send the messages with encryption, they are getting encrypted on disk by default anyway. Try the suggestion in #200 and see if it makes a difference:

> going to Account settings >> End-to-end Encryption >> then disable "Store draft messages in encrypted format" under Advanced settings

**Comment by eastbaytech** [comment]
Upon further inspection you were correct. I went into the account settings under end to end encryption and turned off pgp. I must have played with it in the past. Tests now show correct future sending time in drafts. On Nov 13, 2022, at 1:27 PM, jph-sendlater ***@***.***> wrote:﻿
Closed #468 as completed.
