### ISSUE TITLE
Send Later disables Return Receipts

### ISSUE THREAD

**Issue by benintech** [Extended-Thunder/send-later#474]
Tested in version 9.0.11 (TB102, Debian 11, Gnome 3.38).
But I remember that this bug existed already a few years ago.

Return Receipts are disabled if the mail is sent through Send Later.

**Comment by jikamens** [comment]
This is a [known issue](https://extended-thunder.github.io/send-later/#return-receipts-dont-work) which is not going to be fixed until/unless TB provides an API for Send Later to use to send messages directly rather than going through the Outbox.
