### ISSUE TITLE
Incorrect German translation of Add on's name

### ISSUE THREAD

**Issue by uwe-ss** [Extended-Thunder/send-later#484]
The correct translation of "Send later" is "Später senden" and not "Später Senden". There is no such thing like headline capitalization in German. Seeing this "Später Senden" button hurts my eyes every time; call it nitpicking or not.

"Später Senden" is also inconsistent with the menu item "Später senden" in Datei/File.

I could easily correct it in Crowdin myself but I do not want to vandalize the current translation.

**Comment by jikamens** [comment]
Let's see what the folks over at Crowdin say: https://crowdin.com/project/send-later/discussions/3
