### ISSUE TITLE
"Send all now" option in lower pane status menu

### ISSUE THREAD

**Issue by tamtashi** [Extended-Thunder/send-later#485]
I am missing a function to send all queued email at once (e.g. before shutting down the OS or before closing TB). A good place could be the Button in the lower pane of TB indicating the number of scheduled emails (see screenshot). That would be a nice feature.

![image](https://user-images.githubusercontent.com/82035531/203569652-936b869c-5a44-4e1a-8bf3-80e4e67e6251.png)

**Comment by jph-sendlater** [comment]
I like this idea, but adding new features is not a high priority for me right now. I'll keep this on my radar for when I do have some spare time though!

**Comment by jikamens** [comment]
See also #316.

**Comment by jikamens** [comment]
I think the newly added feature to allow messages in the Drafts folder to be selected and scheduled addresses this user story. You can select all the messages you want to send now, right-click on them, select Send Later > Schedule Message(s) from the menu, and click the Send Now button to send them all.
