### ISSUE TITLE
Can't see preferences with TB dark theme

### ISSUE THREAD

**Issue by scarlion1** [Extended-Thunder/send-later#486]
![image](https://user-images.githubusercontent.com/2446600/204063996-ea965e4b-2aa4-488d-9880-0032019cc944.png)

If I click in the white area (upper left corner for example), then I can Ctrl-A to select all the dialog text, and see the prefs that way... temporarily, at least.

**Comment by vogu66** [comment]
I'm in dark theme but somehow get the opposite effect: my preferences are readable (white on black) while setting for a single message is not.

Note: in the settings, the colors are set to light grey on black with the "always override" option, setting black on white solves the problem so I suspect there is some hardcoded color somewhere.

@scarlion1 : I get the same as you if I set white on white in the colors (Fonts & colors → Colors...) with always override, maybe play around with that? 

Also I'm on Linux with TB 102.4.2, if that can help.

![Screenshot_2022-12-03_12-05-40](https://user-images.githubusercontent.com/24728720/205437828-787143cd-ad46-49bf-a65f-1593daf739bd.png)

**Comment by scarlion1** [comment]
Well if I activate "Use system colors" in TB prefs (with the "Never override" option), then the add-on prefs are readable again at least.  The add-on still does not respect the dark theme, though.

| ![Send Later prefs](https://user-images.githubusercontent.com/2446600/205462515-ca17a6d0-b241-4ab9-9625-68f5538e1a5f.png) |
|:---|
| Send Later prefs|

| ![Send Later message options](https://user-images.githubusercontent.com/2446600/205462608-86450f2b-0655-4f47-8727-2ef7bef42b15.png) |
|:---|
| Send Later message options |

**Comment by jph-sendlater** [comment]
What version of Send Later are you on? I flipped the "browser_style" flag for those UI elements in the latest version. TBH I've never known exactly what that flag does, so it was pretty much randomly set to `false` for the options page, and `true` for the pop-up dialog. Bot are now swapped, but the UI never changed for me (on Linux with Openbox and GTK dark system theme. Both dialogs have always been white regardless of that flag on my system). I'm curious to know if it made any difference for you.

**Comment by vogu66** [comment]
add-on version 9.2.7 for me, for now, and TB 102.6.1. 

~~And, I just checked, now the menu in emails is fine (both with and without the override option), and respects the dark theme, while the writing in the add-on menu is always light-grey.~~

Thunderbird is doing funky things with colors. I still have the same add-on version, but by the time I got around to making snapshots, for the email menu: it's always readable, but it doesn't respect dark theme if the "always override" color option isn't there.

For the add-on menu, nothing changed in the middle of testing, and just like scarlion1 now, if I put the "never override" color option I get black (or dark grey?) on white while the rest of the UI is white/light grey on black. But if I turn on the always override option as I normally do, I get the (same?) black/dark grey for text color while the background changes to dark.

----

For reference:

Dark mode, add-on menu, color always override:
![Dark mode, add-on menu, color always override](https://user-images.githubusercontent.com/24728720/209795451-ee48a03a-bd90-4108-8a57-199f7d072e4b.png)

Dark mode, add-on menu, color never override:
![Dark mode, add-on menu, color never override](https://user-images.githubusercontent.com/24728720/209795520-1de800cb-9eda-4eca-99d7-b8dd4a7b76ab.png)

Dark mode, email menu, color always override:
![Dark mode, email menu, color always override](https://user-images.githubusercontent.com/24728720/209795575-8e50d89a-7097-44a5-a2b1-778187c2c081.png)

Dark mode, email menu, color never override:
![Dark mode, email menu, color never override](https://user-images.githubusercontent.com/24728720/209795600-52718323-2cbb-4dd1-baf9-78d28ad03e1a.png)

**Comment by jph-sendlater** [comment]
This is interesting (and I can actually reproduce it this time). It looks like any element that's set with `"browser_style": true` behaves erratically when "Always override" enabled and a dark theme is specified. I'll switch all elements to `false` in the next release. Thanks for helping track this one down!
