### ISSUE TITLE
"Replied" icon not showing when sent via "Put in Outbox" function

### ISSUE THREAD

**Issue by ehws** [Extended-Thunder/send-later#493]
When replying to an email and then sending with the "Send at..." button, the three configurable buttons or the "Send Now" button an icon indicating a reply is added to the email in the inbox list.
When replying to an email and then sending with the "Put in Outbox" button, this does not appear to happen.

SendLater V9.0.11
TB/BB V102.5.1

**Comment by jph-sendlater** [comment]
Thanks for the heads up. I'll look into this when I get a chance.

**Comment by jph-sendlater** [comment]
This seems to be true initially (i.e. you put the message int the outbox and no reply icon appears), but when the message is actually sent, then the reply icon shows up. Try composing a reply message, using "Put in Outbox" and then trigger the outbox to send unsent messages. Let me know if that isn't the case for you, otherwise I'm going to close this for now.

**Comment by ehws** [comment]
Thank You for looking into this.

I may have fuzzily worded the issue. It was about the consistency of SendLater actions:

1. When replying to an email and then sending with the "Send at..." button, the three configurable buttons or the "Send Now" button an icon indicating a reply is added to the email in the inbox list.

2: When replying to an email and then sending with the "Put in Outbox" button, an icon indicating a reply does not appear.  This icon only appears when the email is actually sent from the Outbox.

Imagine this scenario: a user is responding to a number of emails. Some are responded to by your "Send at..." button, some with your "Send Now" button and some with your "Put in Outbox" button,  The fist two types of email responses are marked as responded to, the last type of email responses is not.

Anyone using the "replied to" icon or a filter rule of "status = replied" to move or delete emails will be confused!

Sorry if this sounds pedantic, but the main reasons for using TB/SL are the idiosyncrasies and annoyances found in commercial email products. 
Thank You
