### ISSUE TITLE
9.24 problems in my installation

### ISSUE THREAD

**Issue by jkohan0** [Extended-Thunder/send-later#495]
Hello. I used send-later for many months now and I´m very happy with it. 
But after Thunderbird extreme lowness, huge use of memory (more than usual ! :-))  I tracked the problem to send later. In safe mode Thunderbirds works well, and disabling 1 by 1 modules could verify it is it. More, I noticed it automatically updated the same day my problems started. 
Cant give you more info for now. Do you need me to make something ?

Thanks for giving out this excellent software.

Regards, 

Javier (Sorry, English is not my native language and don´t trust in translators)

**Comment by igustin** [comment]
Same here.

**Comment by jph-sendlater** [comment]
Thanks for letting me know. I'm closing this because it seems to be covered by #497
