### ISSUE TITLE
Send Later breaks Thunderbird's "Confirm when using keyboard shortcut to send message" setting

### ISSUE THREAD

**Issue by dizzy-egg** [Extended-Thunder/send-later#498]
Send Later breaks the `Settings -> Composition -> Confirm when using keyboard shortcut to send message` setting in Thunderbird.

With Send Later enabled Thunderbird no longer shows a confirmation dialog when I send emails using Ctrl+Return.

I first noticed this on version 102.5.1 but it also happens on the latest 102.6.

A fix, or any ideas to self-fix, would be most appreciated.

Thank you for the useful extension.

**Comment by ooksanen** [comment]
#494

**Comment by jph-sendlater** [comment]
I'm gonna close this one as a duplicate of #494
