### ISSUE TITLE
Replace "Send Now" with "Place in Outbox"

### ISSUE THREAD

**Issue by jperryhouts** [Extended-Thunder/send-later#50]
For consistency with legacy functionality, the popup dialog should present an option to place a message in the outbox, rather than initiating an immediate send operation.

**Comment by rgrun1** [comment]
Could we have both?

**Comment by jperryhouts** [comment]
@rgrun1 Yes, I will implement both.

**Comment by jperryhouts** [comment]
Addressed by #142
