### ISSUE TITLE
Error with sending to multiple contacts from contact group (Contact list in Address Book) after update to 9.2.4

### ISSUE THREAD

**Issue by Kocour-Komiksak** [Extended-Thunder/send-later#502]
If I select one recipient after another, everything is fine, but if I select a group of contacts (Conatact List), email will stuck in Outbox with an error pops (see picture below)

![error after send](https://user-images.githubusercontent.com/120442227/207851560-a998f3de-2197-454e-9152-f544da4f9f81.jpg)

It looks like the group of contacts was not divided into individual contacts when sent and takes the name of the group as one contact with a forbidden ASCII characters "<>" 

![select recepient](https://user-images.githubusercontent.com/120442227/207851620-17a47a4f-21b1-4fe7-84ee-c762864fae42.jpg)

If I revert plugin back to ver. 9.0.11, everything works fine again

**Comment by rgrun1** [comment]
I am having the same issue

**Comment by jph-sendlater** [comment]
Thanks for the bug report! This should be fixed in 9.2.5 (available [on github](https://github.com/Extended-Thunder/send-later/releases/tag/9.2.5) and awaiting approval on ATN)

**Comment by rgrun1** [comment]
Great! It is fixed

Thank you and Merry Christmas
