### ISSUE TITLE
Schedule sending with thunderbird mail merge adds on

### ISSUE THREAD

**Issue by Haitham40** [Extended-Thunder/send-later#505]
Is it possible to add a column in the CVS file containing the required send times ( scheduled times ) then I add it to thunderbird mail merge because I want to send emails separately ( for ex one email every 2 hours ). 
I tried to do that but there is no option to add this during merging. 
Thanks in advance.

**Comment by jph-sendlater** [comment]
That's a question for the MailMerge author.
