### ISSUE TITLE
Send Later preferences don't appear under Tools -> Add-on Options menu

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#51]
There should be a menu command in the Tools -> Add-on Options menu to bring up the Send Later preferences page.

**Comment by jperryhouts** [comment]
Are other extensions doing this in TB78+? My understanding is that Thunderbird is trying to corral extensions into using these centralized options pages within the add-on manager, but I don't know if others have been doing it anyway via experiments. Of the add-ons I've tried, none of them have put an `Add-on Options` item back into the Tools menu.

**Comment by jikamens** [comment]
Yes. Look at ImportExportTools NG.

**Comment by jikamens** [comment]
Apparently this is going away on purpose, so never mind.
