### ISSUE TITLE
Issue about send later(add on)

### ISSUE THREAD

**Issue by o0purist0o** [Extended-Thunder/send-later#510]
Thunderbird add-on About send later, if I set the sending date and time and register it, it will be displayed in the draft, but when the date and time come, it will jump to the sentbox of the local folder, and it will not actually be sent.
The version of send later is 9.2.7. 
Thunderbird is also the latest 102.6.1 (32bit).
Anyone know the cause?

**Comment by jikamens** [comment]
Please follow the steps in [this troubleshooting section](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) if this is still an issue, and reopen this issue if you're still seeing the problem afterward.
