### ISSUE TITLE
In mac dark mode, viewing send later dialog second time appears blank

### ISSUE THREAD

**Issue by toddlash** [Extended-Thunder/send-later#520]
Create a new message, click on the send later button (see options). close the send later dialog. Click send later again (second time) the dialog opens but the content is bank. Looks like the functionality is there because clicking in the area where the buttons are does send later.

**Comment by jikamens** [comment]
@toddlash Still seeing this? If so, what platform are you on, and what TB version?

**Comment by jikamens** [comment]
I believe this is resolved, but please reopen or comment if you're still seeing it in Send Later 9.3.0 for TB109 or 10.0.1 for TB115.
