### ISSUE TITLE
Thunderbird 102.7.0 + Send Later makes program ignore CTRL+ENTER confirmation window

### ISSUE THREAD

**Issue by Balls0fSteel** [Extended-Thunder/send-later#521]
So let me start with this: This is a new issue, it wasn't like this before.

Basically, if you have to Send Later enabled, Thunderbird will NOT show the Send Confirm dialog. I have verified that the relevant option in GUI and config editor is set - and the dialog is only ignored if this addon is enabled.

I think the last Thunderbird update, or the one before broke something in addon functionality.

Let me know if I can help test this any way.

**Comment by jikamens** [comment]
Duplicate of #494.
