### ISSUE TITLE
Segmentation fault on fvwm window manager caused by send later

### ISSUE THREAD

**Issue by lormaccone** [Extended-Thunder/send-later#522]
Sometimes (not always), as soon as I click on the "Send at ... (5 minutes from now)" dialog button, my window manager fvwm3 crashes with a "Segmentation fault". 

This ONLY happens with the "Send Later" add on, I have NEVER had any crashes that were not caused by that. It is consistent over many versions of fvwm, including the (now discontinued) fvwm, in addition to fvwm3. 

fvwm3 1.0.6 (1.0.5-52-gad8e4a0d-dirty)  (But older versions affected too)
Thunderbird 102.6.1 (64-bit) (But older versions affected too)
Send Later 9.2.7
Unfortunately I cannot replicate it consistently, but it does happen at least once every two-three days. Perhaps it has to do with mouse movement as soon as I click that button? I'm not sure.

Thanks for the, otherwise, very nice software!!
Lorenzo

**Comment by lormaccone** [comment]
I haven't had any more crashes since upgrading both fvwm and send later. Perhaps it's resolved?

**Comment by jikamens** [comment]
Closing this issue because (a) the reporter says it's no longer happening and (b) in any case there's no way it's Send Later's fault if the window manager is crashing.
