### ISSUE TITLE
Mail not sent when too much stuff is in the draft folder

### ISSUE THREAD

**Issue by stefan11** [Extended-Thunder/send-later#529]
Hi, I noticed that mail is not sent when too many other mails are in the drafts folder. Maybe the plugin gives up the checking because of some timeout. This is dangerous since without a warning for the user important mail may be stuck without anybody noticing.

I cleaned up the drafts folder and everything works as expected.

Thanks for this otherwise great plugin. =:-)

**Comment by My1** [comment]
it seems to ignore 100 mails and after that straight stops, an error might be useful here

**Comment by Rings4** [comment]
> it seems to ignore 100 mails and after that straight stops, an error/message might be useful here

Omg you're right!!! I was pulling my hair out trying to figure out why the addon mysteriously stopped working. THANK YOU! An error really is necessary here.

**Comment by jikamens** [comment]
Bug found and fixed. Working on getting the fix released. Thanks for reporting this issue!

**Comment by My1** [comment]
> Bug found and fixed. Working on getting the fix released. Thanks for reporting this issue!

no problem, dunno how I specifically found the issue being 100 but likely I crawled in some logs or whatever after someone I know had the issue.
