### ISSUE TITLE
"Send Later" encrypts emails with a pgp key for some reason.

### ISSUE THREAD

**Issue by n0rvik** [Extended-Thunder/send-later#532]
Name Thunderbird
Version 102.9.1
ID 20230328155238

Hi. "Send Later" encrypts emails with a pgp key for some reason. But I have the "Sign only" option in my mail settings.

**Comment by jikamens** [comment]
Sorry for the delay getting back to you about this.

Thunderbird encrypts drafts by default. You can turn this behavior off by unchecking "Store draft messages in encrypted format" in the "End-To-End Encryption" section of the account settings. I am not sure when this preference was added; it may not yet be available in 102.9.1, but it is available in 102.13.0. The Send Later documentation about this is out-of-date; I've made a note to myself to update it.
