### ISSUE TITLE
TB 102.9.1 Linux, Send Later 9.2.9, can't schedule message

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#533]
When I click the Send Later button on a message I'm composing and then the schedule button to send the message five minutes into the future, the draft is not saved with the Send Later headers, the compose window does not close, and I get this error message in the error console:

```
Error: Incorrect argument types for SL3U.setHeader. background.js:160:30
```

The same problem occurred with 9.2.7; I tried upgrading to 9.2.9 to see if that fixed it, but nope.

**Comment by jikamens** [comment]
Two additional pieces of info:

1. This also occurs on the same computer when I upgrade to 102.10.0.
2. This does _not_ occur on another Linux computer on which I am using 102.10.0. I have no idea what the difference is between the two computers that would explain the discrepancy in behavior.

**Comment by jperryhouts** [comment]
Is there a difference in the accounts setup on each machine? E.g. does one use IMAP and the other not? Very mysterious why this would have changed between two minor version updates on ESR Thunderbird.

**Comment by jikamens** [comment]
This problem went away on one laptop it was happening on, and started happening on a different laptop it had previously not been happening on. Ugh, the worst kind of bug.

**Comment by jikamens** [comment]
This is probably fixed, will reopen later if it comes back.
