### ISSUE TITLE
TB 102.9.1 Linux, Send Later 9.2.9, Send Later thinks there are scheduled messages when there aren't

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#534]
I don't currently have any scheduled messages.

Nevertheless there's a red badge on the Send Later button with a 1 in it, and the one draft I do have is showing the "Send Later" header field in the message header even though it's empty.

I imagine these errors in the error console are probably relevant:

```
ExtensionError: Cannot add a hdrRow fill handler for a hdrRow that has not been defined ExtensionUtils.jsm:58:5
Error: Incorrect argument types for columnHandler.setColumnVisible. background.js:860:37\
```

When I delete the one draft I do have (which, again, was not a scheduled draft) the badge on the Send Later button goes away. So it appears to be counting an unscheduled draft as a scheduled draft.

**Comment by jperryhouts** [comment]
Does it happen with any message at all in the Drafts folder, or was there something particular about that message?

Those errors look like they're coming from the column and the header view experiments. I would be surprised if they were directly causing the issues here, but they might be a clue about something else that changed in Thunderbird.

Another weird thing is that [esr102 does not seem to have `ExtensionUtils.jsm`](https://searchfox.org/comm-esr102/search?q=ExtensionUtils.jsm&path=&case=false&regexp=false) at all, but [top of tree does have it](https://searchfox.org/comm-central/source/mozilla/toolkit/components/extensions/ExtensionUtils.jsm). I assume it used to be inherited directly from Firefox, and later got copied over to bundle it with Thunderbird. That change must have happened after version 102, so I would be surprised if it's a cause. But a suspicious coincidence nonetheless.

**Comment by jikamens** [comment]
Can't reproduce any more, whatever the problem is it appears to be intermittent. Some sort of timing issue with loading the add-on, maybe? I dunno.

**Comment by jikamens** [comment]
This is probably fixed, will reopen later if it comes back.
