### ISSUE TITLE
unable to edit "send later" messages after they are created

### ISSUE THREAD

**Issue by Stefanseiner** [Extended-Thunder/send-later#541]
Hello,
is there any possibility to change / edit messages once they are prepared to "send later" ?
I would like to change text and time.
Thanks and regards
Stefan

**Comment by dsoprea** [comment]
Inline with that, I expected to be able to cancel one, which is why I added the add-on in the first place. Yet, there appears to be no way to delete them from the queue, or, at least, to do so _quickly_ before the message fires.

**Comment by jikamens** [comment]
Sorry for the delay getting back to you about this.

Scheduled messages are stored in your Drafts folder. You can edit or delete them from there. If you open a scheduled message for editing the scheduled send is automatically cancelled at open time, so you then have to reschedule it if you want it to be a scheduled message again after editing it.
