### ISSUE TITLE
[Question]: Why is there no calendar for the date anymore ... ?

### ISSUE THREAD

**Issue by Woisek** [Extended-Thunder/send-later#544]
In the title. Some versions ago, when clicking into the date field, there was a calendar popping up. This is now missing.
Would be great to bring this back. 🙂

**Comment by jikamens** [comment]
Sorry for the delay getting back to you about this!

This is interesting: On Linux at least, with TB 102.13.0, if I click on the date field, no calendar pop-up appears, but then if I click in the time field and then click back into the date field, a calendar pop-up appears _in the wrong place_, offset by half the screen from where it should appear on top of the Send Later pop-up.

@jobisoft @jph-sendlater any insights about this?

**Comment by jikamens** [comment]
@Woisek what platform are you encountering this issue on and what TB version?

**Comment by Woisek** [comment]
@jikamens Win7 and TB 91.5.1
It had worked before. I didn't do any updates beyond this version, because new versions kill almost every extension I need to have.

**Comment by jobisoft** [comment]
Lost add-on stats:
- https://thundernest.github.io/add-on-reports/lost-tb91-to-tb102.html

Which one of those are you missing? If it is not one of these, I really urge you to update to 102.

**Comment by Woisek** [comment]
Thanks for the reply. I use those extensions:
BorderColors D (a not so good substitute for the longer not working AccountColors)
changeQuote
EditEmailSubject MX
Header Tools Lite
Mailbox Alert (most important)
Manually sort folders
Quicktext
XNote

Most of them won't work AFAIK ... 😔

**Comment by jobisoft** [comment]
Have you checked the list? All of them work in 102. They do not yet work in 115, but from our experience, after 2 month most authors will have updated.

**Comment by Woisek** [comment]
I don't know ... I had once missed that TB had updated and all the extensions where deactivated. I can't tell which version it was, I just still know how much of a PITA it was to revert all and get it to work again ... 😔

Maybe I try in a VM first. Thanks for looking into it.

**Comment by jobisoft** [comment]
It is true, that directly after each release many add-ons may be broken. Now for example, about 100 add-ons are broken in Thunderbird 115 (released last week). But we work hard to support the developers and get down that number to a single digit value within 2 month.

**Comment by Woisek** [comment]
Thanks for your effort, we all appreciate it. 🙂

**Comment by jikamens** [comment]
The date picker issue appears to be fixed in TB115. There is now a little calendar icon at the right edge of the date field in the picker and if you click on that then a calendar pops up. Please comment that's not what you're seeing.
