### ISSUE TITLE
Please update for Thunderbird 115

### ISSUE THREAD

**Issue by gjf** [Extended-Thunder/send-later#551]
Today Thunderbird 115 was released and the addon was disabled as outdated.

Please update it.

**Comment by dib0** [comment]
For the more adventurous people: a temporary solution is to download the XPI, rename it to a zip-file, alter the file manifest.json from this:
```
  "applications": {
    "gecko": {
      "id": "sendlater3@kamens.us",
      "strict_min_version": "102.0",
      "strict_max_version": "114.0"
    }
```
To
```
  "applications": {
    "gecko": {
      "id": "sendlater3@kamens.us",
      "strict_min_version": "102.0",
      "strict_max_version": "116.0"
    }
```
Rename the zip-file back to XPI and install it from file within Thunderbird.

Do this at your own risk! I did some testing and it all seems to be working correctly, but no guarantees.

**Comment by jikamens** [comment]
We're working on it.

**Comment by telrod11** [comment]
Thanks.   Could not continue to use TB without your Send Later add on!!   :)

**Comment by droumanet** [comment]
Sorry, I've not found this discussion when searching before. (@jikamens )
Thanks for the Workaround @dib0 🙂

**Comment by James6M** [comment]
Using work-around, I don't see the "Send Later" column, and the keyboard shortcut doesn't bind.  Do others see these limitations?  Basic functionality does seem to be working.

**Comment by jikamens** [comment]
There is a now a beta release for TB115. Please try it out! See [this message](https://groups.google.com/g/send-later-users/c/sHSCIYVm83k/m/tRafINw9AQAJ) for details. The corresponding GitHub release can be found [here](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.0).

**Comment by jikamens** [comment]
Release 10.0.1 has been pushed to addons.thunderbird.net and should appear there shortly.
