### ISSUE TITLE
[Dev] Out-of-thread execution in background.js init()

### ISSUE THREAD

**Issue by jobisoft** [Extended-Thunder/send-later#554]
I found async code being executed in `init()` in `background.js`, that is not awaited and therefore is potentially executed at an arbitrary later time:

https://github.com/jobisoft/send-later/blob/master/background.js#L732-L754

This is usually a source of timing related issues, specifically during startup. If there is no reason for this, I would suggest to simply await the call to `SLTools.getPrefs()` and then have the code handling the returned preferences to be sequentially executed.

**Comment by jikamens** [comment]
This could definitely explain the intermittent startup issues which cause the add-on not to initialize properly sometimes. Seems like a pretty straightforward change, I don't see any reason not to do it.

**Comment by jikamens** [comment]
Is your fork current with the Extended-Thunder release? It appears to me that this issue is already resolved there and in the version of background.js in version 9.2.9 on ATN. Am I missing something?

**Comment by jobisoft** [comment]
> Is your fork current with the Extended-Thunder release? It appears to me that this issue is already resolved there and in the version of background.js in version 9.2.9 on ATN. Am I missing something?

https://github.com/Extended-Thunder/send-later/blob/master/background.js#L752-L773

**Comment by jobisoft** [comment]
I forked this repo: https://github.com/jperryhouts/send-later and not the Extended-Thunder repo. The genius I am.
