### ISSUE TITLE
[Dev] Drop all legacy preferences and use local storage

### ISSUE THREAD

**Issue by jobisoft** [Extended-Thunder/send-later#560]
If Experiments need to access preferences, the background can pass in the current values read from storage, so there is no need to access preferences IN other Experiments (where accessing local storage might be difficult).

Edit: Could be that all current usage is used for migration only. I think it is then safe to drop its usage.

**Comment by jph-sendlater** [comment]
Yes, the current usage is from migration, and should be pretty safe to remove at this point.
