### ISSUE TITLE
Please consider supporting TB version 115

### ISSUE THREAD

**Issue by tzenker-tzc-itexperts** [Extended-Thunder/send-later#561]
Dear send later team,
compatibility check for Thunderbird (screen shot below) marked that
Send Later is not compatible with upcoming TB 115.
Please consider supporting TB version 115.

![TB_115_send_later](https://github.com/Extended-Thunder/send-later/assets/117731736/32910408-5295-4676-8350-f76b41bc98b6)

**Comment by arndissler** [comment]
I mark this as a duplicate of #551 (see and track comments over there).
