### ISSUE TITLE
Ctrl+Enter doesn't trigger Send Later.

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#568]
<kbd>Ctrl</kbd>+<kbd>Enter</kbd> doesn't popup the Send Later dialogue box, regardless of whether  `“Send” does “Send Later”` is checked or not, nor does it trigger the "Send at" button when the box is open. Nor does <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> work.

<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> etc. and <kbd>Ctrl</kbd>+<kbd>1</kbd> etc. do not work (again, regardless of `“Send” does “Send Later”`). What's strange is that if I make a new message, don't specify a recipient or subject, and hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd>, the "Invalid Recipient Address" dialog box pops up, but if I fill out the subject, body, and recipient address, <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> doesn't do anything.

<kbd>Ctrl</kbd>+Click and <kbd>Shift</kbd>+Click accelerator keys work.

<sub>I wonder if some of the above problems have to do with my my custom Xmodmap; `xev` says the key is "Return" (not "Enter"), and I've bound <kbd>ctrl</kbd> and <kbd>ctrl</kbd> to other keys.</sub>

I'm using Thunderbird 115 with Send Later 9.2.9, though I've had this problem for quite awhile with previous Thunderbird and Send Later versions. I've tried refreshing Thunderbird with the Troubleshooting Mode, but I still get the same problems.

**Comment by jikamens** [comment]
Send Later 9.2.9 is not compatible with Thunderbird 115, so I'm not sure how you're doing that.

Please try the [beta release for TB115](https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.0) and see if the problem persists.

**Comment by jikamens** [comment]
Please reopen this issue if you are still seeing it with Send Later 10.0.1 (which was just released and will show up on addons.thunderbird.net shortly) or comment if you are unable to reopen (I don't know whether Github will allow you to reopen the issue) in which case I will investigate further.

Also, if you're still seeing the issue please let me know details of what platform you're using (OS, OS version, desktop, etc.).

**Comment by Geremia** [comment]
@jikamens No, I can't reopen this issue, so I've opened #583.
<kbd>Ctrl</kbd>+<kbd>Enter</kbd> is the only shortcut that works now!
