### ISSUE TITLE
Make it possible to schedule multiple unscheduled drafts at the same time

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#585]
Suggested in https://addons.thunderbird.net/en-US/thunderbird/addon/send-later-3/reviews/1168899/:
>Make it possible to use this add-on for a variety of emails. For example, in the list of emails. For 5 selected emails - apply the "Send within a week" function (or others).

**Comment by jikamens** [comment]
Implemented in https://github.com/Extended-Thunder/send-later/releases/tag/v10.0.6

**Comment by misaki-web** [comment]
It doesn't work with Send Later v10.1.3 on Thunderbird v102.13.0.

When I select multiple drafts and try to schedule these messages, nothing happens. For example, if I choose to schedule in 5 minutes, the popup doesn't close when I click on the button, and the Send Later column stays empty.

However, if I select only one draft, it works. If I choose to schedule in 5 minutes, the popup closes and the Send Later column is updated. Then, 5 minutes later, the message is sent.

**Comment by jikamens** [comment]
> It doesn't work with Send Later v10.1.3 on Thunderbird v102.13.0.
> 
> When I select multiple drafts and try to schedule these messages, nothing happens. For example, if I choose to schedule in 5 minutes, the popup doesn't close when I click on the button, and the Send Later column stays empty.
> 
> However, if I select only one draft, it works. If I choose to schedule in 5 minutes, the popup closes and the Send Later column is updated. Then, 5 minutes later, the message is sent.

Moved to #626. In the future please don't add comments about new problems to closed issues; create a new issue instead.
