### ISSUE TITLE
Corrupt drafts folder issue - fix is not working

### ISSUE THREAD

**Issue by KluviM** [Extended-Thunder/send-later#605]
I have that issue again. Described in https://extended-thunder.github.io/send-later/#corrupt-drafts-folders
This time I am not able to get rid of message displayed in "send later" toolbar.
I tried some other combinations, emptied entire draft folder (relevant to frozen message), played with offline mode etc. Restarted TB, repaired also SENT folder etc
Nothing helps.
I am quite screwed, can someone help me, please?
Martin

**Comment by jikamens** [comment]
What version of Thunderbird, on what OS?

What version of Send Later?

Where is your email account (e.g., Gmail, Hotmail, etc.)?

Have you tried creating a new, clean Thunderbird profile to see if the problem persists in a new profile?

**Comment by zephyrus9MA** [comment]
I have this exact problem. Thunderbird 115.7.0, Windows 11, Gmail, Send later 10.3.6. Additional info: deleting drafts causes them to remain in the Drafts folder but crossed out. New profile is irrelevant since I need to keep the one with the problem. Will have to disable send later....

**Comment by jikamens** [comment]
The problem you're having is #675. This issue (i.e., the one I'm commenting on right now, #605) is fixed, so closing.
