### ISSUE TITLE
Is it safe to turn S/MIME back on?

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#613]
After 10.1.0 was released a user emailed and informed me that he had been using Send Later with S/MIME just fine for the longest time with no trouble.

I need to look into whether it's safe to turn it back on. I am concerned that there may be infornation leakage in the signed messages, e.g., they might contain the date when the user wrote and scheduled the message as opposed to the date when it was delivered by Send Later.

**Comment by jikamens** [comment]
@EvilRunner This bug ticket is separate from the problem you describe.

Regarding the problem you're having, it's fixed in the release that was approved on addons.thunderbird.net a few hours ago. If you go to the add-ons page in Thunderbird and click on the gear icon and select check for updates, it should get the new update, which should resolve the problem. Or it could have already updated automatically since you commented here. Check the version of Send Later by clicking on it on the add-ons page to open its properties. If it says 10.1.1, you should be all set. If you've got 10.1.1 and it's still not working, open a net ticket; please don't continue this discussion on this ticket because it's about something else.

**Comment by EvilRunner** [comment]
just checked, thanks !

**Comment by jikamens** [comment]
We did indeed determine that it was safe to turn S/MIME back on, so we went ahead and did that in 10.1.3!
