### ISSUE TITLE
Request: Send Later pop-up screen size

### ISSUE THREAD

**Issue by LeslieDesser** [Extended-Thunder/send-later#619]
I have my screen set at 150%.  Depending on the position of the message window on the screen, when using Send Later, the bottom of the pop-up screen is often not visible - so cannot click 'Send Now' as it cannot be scrolled or moved.

You now have the ability to re-size the pop-up - excellent.

Request: After re-sizing, the new size should be remembered for future pop-ups.

**Comment by jikamens** [comment]
Hmm.

If you customize the compose window toolbar and remove the Send Later button on TB115 (you can't do this on TB102), then Send Later's pop-up will show up as a separate window that can be scrolled, resized, and moved.

Send Later has no control over the size of the pop-up when it's attached to the toolbar button, but I could remember the zoom setting and preserve that in this situation. Would that be useful.

If it's a separate pop-up window, i.e., if you've removed the Send Later button from the toolbar as described above, then Send Later does have the ability to remember and restore both the size and the zoom level. Would that be useful?

**Comment by LeslieDesser** [comment]
I'm on TB102 - not been offered 115 yet.  If the behaviour changes for 115 then I do not think it worth while to do anything more in 102.

If I remember to place the message window up to the top of the TB window then I can see all options on the pop-up - so can continue with it as is.

PS: The Send Now button has an underline on the N - how is that triggered without the mouse?

**Comment by jikamens** [comment]
Access keys like the 'N' are Alt+Shift+key on Windows and Linux or Ctrl+Option+key on macOS.

**Comment by LeslieDesser** [comment]
Thank you - that solves my problem in the simplest way.

**Comment by jikamens** [comment]
FYI in the next release the zoom level will be saved between invocations of the pop-up, and if you use the detached pop-up then its dimensions will also be saved (I can't control the dimensions of the pop-up when it's attached to the Thunderbird window).

**Comment by LeslieDesser** [comment]
Thank you.  I will report back when I try it.
