### ISSUE TITLE
As of 10.1.0 Send Later is corrupting emails with non-ASCII characters in them?

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#620]
I have a report from a user who sends emails in Czech claiming that Send Later is corrupting their emails as of 10.1.0.

I can't reproduce this so I've asked the user for more details, but I wanted to file this issue in the meantime to make I remember to follow up.

**Comment by digitarenet** [comment]
Also for me the same problem... "è" has been translated to "Ã¨" after the email has been sent.
The same issue occurs for other letters: àòùé....

Thunderbird version: 115.1.1
Send Later version: 10.1.1

**Comment by digitarenet** [comment]
MacOs 13.5.1 platform...
Now I have updated Thunderbird to v115.2.0, same issue.
I send you 2 emails for test: one with and one without SEND LATER.

**Comment by digitarenet** [comment]
These are emails sent you in my sent folder:

Without SEND LATER:
<img width="409" alt="S 2023-08-30 alle 16 34 39" src="https://github.com/Extended-Thunder/send-later/assets/11545221/58932a37-95f8-45e1-b3cb-30fc8392fc5c">

With SEND LATER:
<img width="422" alt="S 2023-08-30 alle 16 34 31" src="https://github.com/Extended-Thunder/send-later/assets/11545221/48797fd3-b665-4a91-ad9b-0938b79338bb">

**Comment by mbfdias** [comment]
Just did a quick test and I can confirm the problem in the body of the email. The subject is ok

![image](https://github.com/Extended-Thunder/send-later/assets/6865169/b8306bee-5645-4b0b-ade2-beae2ef376f9)


![image](https://github.com/Extended-Thunder/send-later/assets/6865169/373eb91e-076d-42d8-9c06-1d1381dd8e94)

**Comment by jikamens** [comment]
I'm scratching my head here. I'm unable to reproduce this. Here are the tests I've tried, on macOS Ventura:

1. Copy the accented text from Andrea's email into an email sent without Send Later; it arrives fine.
2. Copy the accented text from Andrea's email into an email sent with Send Later; it arrives fine.
3. Change my UI language to French and repeat the above two tests; they work fine.
4. Change my macOS primary language to French and repeat the above two tests; they work fine.

I can't find any settings in Thunderbird that control how emails are encoded so I don't know what else to try.

Any thoughts about what might be different at your end?

**Comment by mbfdias** [comment]
source without sendlater
![image](https://github.com/Extended-Thunder/send-later/assets/6865169/258e58fe-82a6-49d6-b071-eff64de2144e)

source with sendlater
![image](https://github.com/Extended-Thunder/send-later/assets/6865169/5e55a26b-9caf-4dd4-a9bb-607356ea685a)

**Comment by digitarenet** [comment]
I not foud encoding settings.
I'm using Fixed lenght FONT (Menlo) for emails.
I also use "Thunderbird Language Pack for Italiano (it) – Italian" v.115.2.20230828.145448

These are my settings:
<img width="834" alt="S 2023-08-30 alle 17 06 06" src="https://github.com/Extended-Thunder/send-later/assets/11545221/0dba43f5-7f5c-4af1-9ea5-e85e0e59e087">

**Comment by jikamens** [comment]
Aha! I've reproduced the issue.
Don't send me any more sample emails please. ;-)
Stand by while I try to figure out what the heck is going on.

**Comment by jikamens** [comment]
This is fixed in the new version which I just uploaded to addons.thunderbird.net. If you don't want to wait for the moderators to approve it and for your Thunderbird to notice the update, you can update immediately from the release file stored on GitHub as follows:

* Download [this file][xpi] and save it to your local computer. If you're reading this in Firefox, make sure to right-click on the link and select "Save Link As..." rather than just clicking on it, or Firefox will try to install it as a Firefox add-on.
* Open the Add-ons page in Thunderbird (Tools > Add-ons and Themes).
* Click the gear icon at the top.
* Select "Install Add-on from File...".
* Browse to the file you saved and select it.
* Click through the dialogs to confirm installation.
* You can delete the downloaded file once you've installed it.

If you don't want to do this you can wait until the moderators approve it, though I can't say whether that will take hours or days.

I'm sorry about these bugs and I thank you for your patience as I've fixed them as rapidly as I could.

[xpi]: https://github.com/Extended-Thunder/send-later/releases/download/v10.1.3/send_later.xpi

**Comment by digitarenet** [comment]
I have tested. All works fine now.
Thanks!
