### ISSUE TITLE
Scheduling multiple messages not working in TB102

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#626]
It doesn't work with Send Later v10.1.3 on Thunderbird v102.13.0.

When I select multiple drafts and try to schedule these messages, nothing happens. For example, if I choose to schedule in 5 minutes, the popup doesn't close when I click on the button, and the Send Later column stays empty.

However, if I select only one draft, it works. If I choose to schedule in 5 minutes, the popup closes and the Send Later column is updated. Then, 5 minutes later, the message is sent.

_Originally posted by @misaki-web in https://github.com/Extended-Thunder/send-later/issues/585#issuecomment-1704339065_

**Comment by jikamens** [comment]
Thank you for the report, I will look into it.

**Comment by jikamens** [comment]
@misaki-web I have tested this on Linux, Windows, and macOS and cannot reproduce it. Please see the attached video which show how it behaves for me on all three platforms. Do you notice any differences between what I'm doing and what you're doing that might explain why it works for me and not for you?

[Screencast from 2023-09-03 13-20-28.webm](https://github.com/Extended-Thunder/send-later/assets/1598067/e094cc2a-f6b1-4fef-a8a8-ada268247b3f)

**Comment by misaki-web** [comment]
@jikamens Thanks. My steps are the same as in the video. I'm on Xubuntu 23.04. I tried to find out more, and it seems that it works as expected (as in the video) when I'm testing with drafts on an IMAP account, but it doesn't work when the drafts are in "Local Folders".

**Comment by jikamens** [comment]
Aha! The Local Folders thing is the key. I've fixed this and will release a new version with the fix soon.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.1.5 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.1.5) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.1.5/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.1.5 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by misaki-web** [comment]
I no longer experience the bug with Send Later v10.1.5. Thanks a lot for this really quick bug fix!
