### ISSUE TITLE
Figure out how to store scheduled messages in a separate folder

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#635]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have unscheduled and scheduled drafts mixed together in the same folder, especially for users who have a lot of drafts.

**Describe the solution you'd like**
I would like Send Later to store its scheduled messages in a separate folder, or at least to offer that as an option.

**Additional context**
It turns out that Thunderbird treats messages that are in subfolders of Drafts as drafts themselves, so this actually should be possible to implement, as long as we restrict the feature to subfolders of the user's Drafts folder.

**Comment by jikamens** [comment]
This issue should be fixed in release 10.2.0 of Send Later. To check what version of Send Later you have:

* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Extensions on the left if you're not already on the left if you're not already there.
* Find Send Later in the list of extensions and click on it to open its details page.
* The version number should be displayed there next to
"Version".

This release is not yet available for download from addons.thunderbird.net, but you can download and install it from its [GitHub release page](https://github.com/Extended-Thunder/send-later/releases/tag/v10.2.0) as follows:

* Download [this file](https://github.com/Extended-Thunder/send-later/releases/download/v10.2.0/send_later.xpi) to your computer. (If you are using Firefox, make sure to right click on the link and select
"Save Link As..." rather than just clicking on it, because otherwise Firefox will try to install it as a Firefox add-on.)
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click the gear icon at the top and select "Install Add-on From File...".
* Browse to and select the downloaded file.
* Click through the installation pop-ups.
* You can delete the downloaded file once you've installed it into Thunderbird.

Note that this is a prerelease. While we make every effort to ensure that prereleases are stable, they are a bit more likely to have bugs, so proceed with caution.

If you prefer to wait, the release will eventually be available on addons.thunderbird.net, and unless you've turned off automatic add-on updates, Thunderbird will eventually update to the new version automatically. To update immediately once it's available:

* Go to [addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/versions/) and confirm that release 10.2.0 is available for download there.
* Open the Add-ons page in Thunderbird ("Add-ons and Themes" from the corner "hamburger" menu).
* Click on Send later.
* Click the gear icon and select "Check for Updates".
* The add-on should update and then you should see the message, "Your add-ons have been updated," next to the gear icon.

Please let me know if you still see this issue in this release.

**Comment by andreamoretti** [comment]
Hello,
I'm testing this version. Very useful the folder dedicated to scheduled mails, but I found a bug: everytime I open the send later window is smaller than the last time and I have to manually zoom it.
Thank you for your work!

Andrea Moretti

![Schermata 2023-09-18 alle 04 12 28](https://github.com/Extended-Thunder/send-later/assets/8715994/2003ab39-7228-474a-a558-cbfd61255ec7)
