### ISSUE TITLE
SendLater header appears on all emails

### ISSUE THREAD

**Issue by Geremia** [Extended-Thunder/send-later#637]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

"Send Later 4/9/2023, 04:59" header appears on all emails, both those scheduled to send by SendLater and those not (such as emails in my inbox). This header appears regardless whether I have "Show Send Later Header" checked or not.

I'm using SendLater 10.1.9.

### Operating System

Linux

### Operating System Version

slackware64-current

### Thunderbird version

115.2.0 (64-bit)

### Send Later start-up string

Send Later version 10.1.9 on Thunderbird 115.2.0 (20230829220959) [linux x86-64] UI locale en-US, Date Locale it-IT

**Comment by Geremia** [comment]
I restarted Thunderbird, and the issue was resolved. It seemed to be a Thunderbird and/or SendLater "hot-swappable" updating issue.

**Comment by jikamens** [comment]
Glad it's working for you, but if it happens again, let me know. If so, then I'd like to capture some logs from your TB to see if I can figure out what's going on and fix it.
