### ISSUE TITLE
Send later popup closes directly

### ISSUE THREAD

**Issue by jarlebring** [Extended-Thunder/send-later#657]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

When I press the button "send later", the popup window shows up for a millisecond but then disappears.  This started happening very recently. 

The error console says:
```
sendRemoveListener on closed conduit sendlater3@kamens.us.274877908067 [ConduitsChild.sys.mjs:108](resource://gre/modules/ConduitsChild.sys.mjs)
```

### How to reproduce

1. Compose an email
2. Click on the send later button

### Expected behavior

The popup should not close

### Additional context

It worked up until a couple of days ago. 

### Operating System

Ubuntu

### Operating System Version

20.04.3 LTS

### Thunderbird version

115.3.1 (64-bit)

### Send Later start-up string

Send Later version 10.2.10 on Thunderbird 115.3.1 (20230928194049) [linux x86-64] UI locale en-US, Date Locale sv-SE

**Comment by jarlebring** [comment]
Screen cast:  ![vokoscreen-2023-10-12_11-15-30](https://github.com/Extended-Thunder/send-later/assets/11163595/0b6190cc-6a63-434a-b288-f42053444b6e) 

 Pointer was not captured in the screen capture.

**Comment by jikamens** [comment]
I don't really understand why—I think it's probably a TB bug of some sort, but I'm not certain—but this seems to happen when your compose window is close to the edge of the screen. If you move the window away from the edge of the screen it should start working again. Let me know if that doesn't work.

**Comment by jarlebring** [comment]
That didn't help. However, when I connect a different monitor the problem disappeared. I would guess it has something to do with the window manager or thunderbird - so less likely a bug here.  I'll close the issue and it can be re-opened if others report substantial problems in this direction.
