### ISSUE TITLE
Error upon SendLater Sending Message

### ISSUE THREAD

**Issue by Theddie** [Extended-Thunder/send-later#660]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

When any scheduled message is sent by SendLater, I get the following error message via a popup window:

Sending of the message failed.
An error occurred while sending mail. The mail server responded:
Bad recipient address syntax.
Please check the message recipient "'[recipient address]'" and try again.

See the attached screenshot. The given recipient address [recipient address] -- removed from the screenshot -- is correct. The window is stacked, so it takes three clicks on OK to get the message to disappear. The email does get sent, though -- and this only confirms that SendLater was configured correctly with regard to the recipient address.

Configuring SendLater anew did not help. Any help would be greatly appreciated. The problem has been persisting since months and older versions of both TB and SL. Both TB and SL are up to date.

### Operating System

Windows 10

### Thunderbird version

up to and including 115

**Comment by Theddie** [comment]
![SendLater](https://github.com/Extended-Thunder/send-later/assets/15087211/bbf50cce-9ac6-4b73-9a4d-afcecc6cd18f)

**Comment by jikamens** [comment]
My guess is that you have a message with a bad address format in your Outbox. Thunderbird is attempting to redeliver that message and failing every time Send Later delivers another message successfully through the Outbox. Remove the bad message from your Outbox and the problem will go away.

**Comment by jikamens** [comment]
(The Outbox is underneath Local Folders.)
(Note that the error message above is coming from Thunderbird, not from Send Later. By the time it gets this far in the delivery process Send Later is completely hands-off.)

**Comment by Theddie** [comment]
That was it! Thank you very much!
