### ISSUE TITLE
HTML formatting is lost in some (all?) cases when saving draft

### ISSUE THREAD

**Issue by nylimited** [Extended-Thunder/send-later#667]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

I use "Compose messages in HTML format" setting of Thunderbird which is lost after saving the draft.

### How to reproduce

Create a new email or edit an existing one.
Enter some text and make the text larger with Thunderbird's font formatting (see image 1)
Save the draft to be sent at any later time.
Note that the large font has now been lost, reduced to standard font.

Creating the same email and same increased font but using the close and save option of Thunderbird - in other words, bypassing Send Later - keeps the font as it was in the editor and does not lose formatting.  This makes me think the issue is in Send Later.

### Expected behavior

I would expect the font to be saved as it was in the editor which is the normal behavior in Thunderbird.

### Operating System

Linux Mint

### Operating System Version

21.2 (Victoria)

### Thunderbird version

115.4.3

### Send Later start-up string

Nothing shows up following those instructions ...

**Comment by nylimited** [comment]
Please note attached 
![saved_draft](https://github.com/Extended-Thunder/send-later/assets/4739593/e32b799b-5039-4ca6-a51f-85a1a1710865)
![In_editor](https://github.com/Extended-Thunder/send-later/assets/4739593/d8ebeadf-2582-47d1-b35d-578f7313e59a)
images of text in editor and as a saved draft

**Comment by nylimited** [comment]
I am wondering if this is a Thunderbird rendering issue since when the email as actually sent it will arrive with the correct large font.  I have not actually tried to edit a draft without switching the apparent small font back to large again and send it to see what arrives..

**Comment by jikamens** [comment]
This is simply a matter of your Zoom setting in the composition window being different from the Zoom setting in the preview pane, I think.
In any case, as you point out when you edit the draft the size is correct, so Send Later isn't changing anything as you claimed at the top of the ticket.
Nothing I can do about how Thunderbird displays drafts in the previous pane.
