### ISSUE TITLE
Send Later does bad things if throttleDelay is so big that it takes more than check interval to send all the messages

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#669]
Apparently still not fixed:
Now using SL Version 10.3.3 Last Updated October 28, 2023 TB 115.5.0 (64-bit) on Ubuntu up to date
Mail merge from a list (only using a few emails in the list for now).
Sendlater   "throttleDelay": 600000, (I also tried adding another zero with no apparent effect)
Put debugging on Trace and saw nothing helpful - it sent the messages all at once - then said it was waiting 60 seconds 

I am thinking I could simulate this by setting up individual times for each email address in the merge file as a column to put in the send field or some such thing - but that seems a bit too crazy.
Or perhaps I could have an external shell script that somehow pushes a message to be sent into TBird every minute or so?
Any other suggestions or work arounds?

_Originally posted by @fc0 in https://github.com/Extended-Thunder/send-later/issues/503#issuecomment-1837433729_

**Comment by jikamens** [comment]
I can't really provide the kind of detailed support you're looking for here, but the basic idea is to create a Mail Merge compatible spreadsheet containing all the recipients, with a column for the send time of each message. Put the send time of the first message in the first recipient row of the spreadsheet and then use a formula in all the subsequent rows to increment the time by one minute. Then you can save that as a CSV and use the CSV to do the mail merge. The Send Later user guide explains how to use columns from the CSV to specify the send date and send time. If you have so many messages that the send time rolls over into the next day then you'll have to be a bit cleverer and use a formula to calculate the date/time, not just the time, and insert that date/time into the Mail Merge.

**Comment by fc0** [comment]
Got it - The simplest way is to simply use Mail Merge -> Send Now with Pause set to 60 seconds. The interface stays open as it goes through one after the other - no problem.

**Comment by jikamens** [comment]
It turns out the problem wasn't that main loop runs were overlapping, it was that `forAllDrafts` was timing out each message send after five seconds even though the throttle delay was much larger than that. It'll be fixed in the next beta not to do that, but it's still a bad idea to use large values for throttleDelay.
