### ISSUE TITLE
Send later requires "full, unrestricted access to Thunderbird and your computer"

### ISSUE THREAD

**Issue by iaeiou** [Extended-Thunder/send-later#67]
The permissions asked are a bit wide, could anyone please reconsider this aspect?

![send-later](https://user-images.githubusercontent.com/69427615/97946869-e4219d80-1d8b-11eb-8bbf-3194299b6830.png)

**Comment by jperryhouts** [comment]
Many of the functions that Send Later uses are not part of the official API yet, so it needs to run parts as "experiments" which have access to Thunderbird's internals. That's how all addons used to work, but now they come with a scary warning. You'll get the same thing from a lot of other addons right now that have not yet integrated with the (underdeveloped) API.

Anyway, all that is to say that we have no option, but eventually this will go away when the extension API matures enough.

**Comment by ivanperez-keera** [comment]
Sorry for commenting on an old issue. It's almost 3 years later. This warning keeps coming up.

Do you think this could be "fixed" now?

**Comment by jikamens** [comment]
If we could fix it we would have.
