### ISSUE TITLE
please add a button to delete the qued emails

### ISSUE THREAD

**Issue by Scott16546** [Extended-Thunder/send-later#680]
**Describe the solution you'd like**
please add a button to delete the qued emails

![Screenshot 2024-02-11 at 16 21 22](https://github.com/Extended-Thunder/send-later/assets/82477557/0fa2cd42-cdc0-4ed7-ba71-ac5bd97ea942)

**Comment by jikamens** [comment]
I am not going to do this.
It's a risky operation and therefore not one that I want to make easy like you're proposing.
As I said in the other ticket, you can delete messages from your Drafts folder.
Please do not open another issue about this.
