### ISSUE TITLE
SendLater emails never moved to Outbox

### ISSUE THREAD

**Issue by Jack-Reid** [Extended-Thunder/send-later#688]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

When I try to send an email at a specified time, the X-Send-Later header is correctly added to the message. However, at the specified time, the message remains in Drafts and is not moved to Outbox.

Three errors appear in the Error Console:
```
ERROR [SendLater]: Something went wrong while sending message
[Exception... "Not enough arguments [nsIMsgCompUtils.msgGenerateMessageId]"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"
ERROR [SendLater]: Error sending raw message from drafts Error: An unexpected error occurred
```
Each occurs repeatedly, as though Send Later attempts many times to send the message.

None of the typical solutions offered in the User Guide resolve this.

Having tried with multiple email accounts, the same issue arises.

### Operating System

Windows

### Operating System Version

Windows 10

### Thunderbird version

115.8.0

### Send Later start-up string

Despite disabling and re-enabling SendLater, no message including the word 'locale' appears in the Error Console.

**Comment by jikamens** [comment]
What version of Send Later do you have installed?

**Comment by jikamens** [comment]
I am unable to reproduce this issue with version 10.4.0 of Send Later. The current version of Send Later never calls msgGenerateMessageId, and the last version that did is version 9.1.1, which was released a long time ago and is no longer supported and I can't imagine would still be compatible with Thunderbird 115.8.0. I find it hard to believe you would even be able to convince Thunderbird to run version 9.1.1 of Send Later in version 115.8.0 of Thunderbird. So overall I'm mystified by this bug report.
I also checked the Thunderbird source code and all the calls to msgGenerateMessageId I could find appear to have the correct number of arguments.
It seems possible that there is another add-on generating this error. :shrug: What other add-ons do you have installed? If you disable the others are you still able to reproduce this issue?

**Comment by Jack-Reid** [comment]
Thank you for you reply. I understand the problem. I had SendLater v. 8.0.2. In order to keep my add-ons up to date, I had been relying on Tools > Add-ons and Themes > Check for Updates. For some reason, this did not work for SendLater, and did not report any updates, but did for the others. Having removed the old version of SendLater, and installed the new fresh from the Mozilla website, everything works perfectly.

Thank you for your help and apologies for the trouble.
