### ISSUE TITLE
HTML formatted emails become plain text

### ISSUE THREAD

**Issue by ribz** [Extended-Thunder/send-later#69]
If a message is written using HTML formatting and Send Later is used, the message that appears in Drafts is the 'plain text' version - all formatting gets stripped.

**Comment by jperryhouts** [comment]
This may be related to #60 for which a fix exists in the master branch, but has not yet been included in a release. I'll ping you again about this after the next release to see if it's still happening.

**Comment by jperryhouts** [comment]
@ribz following up, does this problem still exist in the latest release?

**Comment by ribz** [comment]
Just tried in 8.2.1 and the issue is fixed.

Thank you!

**Comment by jperryhouts** [comment]
Great. That's good to hear!
