### ISSUE TITLE
Office365 and Gmail Accounts

### ISSUE THREAD

**Issue by infinitelyintrigued** [Extended-Thunder/send-later#697]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

I use Send Later 10.3.6.
I have two accounts: Gmail and Office365 (via Owl for Exchange https://www.beonex.com/owl/).
Both accounts are selected to send later.
When I create an Office365 email to be sent later, it goes out using my Gmail account. (The recipient sees my Gmail address as the sender.)
However, when I create a Gmail email to be sent later, it goes out using my Gmail account, as expected.
It appears no matter which account I use, Send Later always chooses my Gmail account to send.

### How to reproduce

1. Compose an Office365 email message. (The identity is set to my Office365.)
2. Schedule it to be sent later using Send Later. (The message goes out as scheduled.)
3. The recipient see my Gmail email address as the sender.

### Expected behavior

When I use the Office365 account, the recipient sees my Office365 email address.

### Operating System

Linux

### Operating System Version

6.8.0

### Thunderbird version

115.9.0

### Send Later start-up string

Send Later version 10.3.6 on Thunderbird 115.9.0 (20240320095953) [linux x86-64] UI locale en-US, Date Locale en-US static.js:146:28

**Comment by jikamens** [comment]
You checked the box in this bug template claiming that you consulted the user guide, but either you didn't or you somehow missed this section that already answers your question:

https://extended-thunder.github.io/send-later/#owl-for-exchange-add-on
