### ISSUE TITLE
Known issues in the beta release

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#7]
* If you edit a scheduled draft and reschedule it, the newly scheduled draft might not get recognized / delivered by Send Later at the scheduled time, unless you quit and restart Thunderbird.
* The add-on's options page is broken in the current Thunderbird 79 beta release due to a bug in Thunderbird.
* Send Later currently does not warn you if you exit Thunderbird when there are scheduled messages, as it does in Thunderbird 68.
* There is not yet a Send Later column in the message list in the drafts folder.
* There is not yet Send Later info in the status bar at the bottom of the main Thunderbird window.
* The option to prevent triggering delivery of messages from the Outbox currently is not available.

**Comment by rgrun1** [comment]
You cannot save the current time defaults
If you schedule a send for a later date and choose a time earlier than the current time, it will not schedule a time in the past. i.e It is 10 am now on 7/31. If i choose to send on 8/1 at 9am. sendlater thinks it is an ealier date

**Comment by jperryhouts** [comment]
Thanks. I can confirm that happens to me as well. I'll look into it tomorrow morning.

**Comment by jperryhouts** [comment]
> You cannot save the current time defaults
> If you schedule a send for a later date and choose a time earlier than the current time, it will not schedule a time in the past. i.e It is 10 am now on 7/31. If i choose to send on 8/1 at 9am. sendlater thinks it is an ealier date

Should be fixed by https://github.com/Extended-Thunder/send-later/pull/8 -- If you installed from the xpi release, there's a new .xpi for the patched version [here](https://github.com/Extended-Thunder/send-later/raw/master/release/send_later-8.0.2-tb.xpi)

**Comment by jperryhouts** [comment]
I'm going to lock this issue, and encourage people to create new issues for new bugs. Keeping them in this one place will get complicated otherwise.

**Comment by jperryhouts** [comment]
The option to prevent triggering delivery of messages from the Outbox is now available in version 8.0.4

**Comment by jikamens** [comment]
@jperryhouts can you generate a release?

**Comment by jperryhouts** [comment]
@jikamens Yes, the most recent release is up to date with the baster branch:  
https://github.com/Extended-Thunder/send-later/raw/master/release/send_later-8.0.5-tb.xpi

**Comment by jikamens** [comment]
> @jikamens Yes, the most recent release is up to date with the master branch:
> https://github.com/Extended-Thunder/send-later/raw/master/release/send_later-8.0.5-tb.xpi

I mean like create a release on Github [here](https://github.com/Extended-Thunder/send-later/releases), since that is were people should be able to go to find out about releases and to find release artifacts (i.e., download files).

**Comment by jperryhouts** [comment]
Oh, sorry. Yes, I added a new release there as well.

**Comment by jperryhouts** [comment]
Drafts column is re-implemented in [version 8.0.6](https://github.com/Extended-Thunder/send-later/releases/tag/8.0.6).

**Comment by jperryhouts** [comment]
I broke the remaining bullet points out into their own issues to simplify bug tracking. Closing this issue to tidy things up.
