### ISSUE TITLE
Send later does nothing | Send works normally 

### ISSUE THREAD

**Issue by barnez** [Extended-Thunder/send-later#70]
I have installed the latest development version of Send Later. It is installed on Thunderbird 78.4.0 with Windows 10 (v.1909). If I prepare an email (recipient address + subject + some message body text) and select Shift+CTRL+Return or File >> Send Later, nothing happens. There are many errors listed in the Console (see attached)
[log.txt](https://github.com/Extended-Thunder/send-later/files/5485881/log.txt). Disabling the only other add-on (Move Messages and Yourself1.6)) does not help. Send works as normal. Also attached is the Troubleshooting Information
[log2.txt](https://github.com/Extended-Thunder/send-later/files/5485917/log2.txt).

**Comment by jperryhouts** [comment]
The errors in the debug log are probably related to #16, which isn't related to the popup dialog opening.

I don't know about the popup dialog, but I'm guessing it might be related to #19 -- do you have the toolbar visible, and a "Send Later" button in the toolbar of your message composition window?

**Comment by barnez** [comment]
I have the toolbar visible but there is no "Send Later" button in the toolbar (https://snipboard.io/DM7UiK.jpg), only an option in the File dropdown menu.

**Comment by jperryhouts** [comment]
Try right clicking somewhere in the toolbar (near "Attachments") and using "Customize" to add the Send Later button. It usually gets added automatically when you install Send Later, but apparently not in all cases. Let me know if that fixes the problem for you.

**Comment by barnez** [comment]
Adding the Send Later button to the toolbar fixes the issue. Once the button is set in the toolbar, the Shift+CTRL+Return command works to open the dialogue box to set the time to send the email, and once set the emails send as scheduled. Thanks for your help!

**Comment by jperryhouts** [comment]
Glad to hear it.
