### ISSUE TITLE
Time information mismatch.

### ISSUE THREAD

**Issue by AndrewPrzelucki** [Extended-Thunder/send-later#704]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

There is a time mismatch, when setting the minutes, between what is selected and what is shown in the button. This never happened before (I'm using this plugin since about a year). Here are some pics:

![image](https://github.com/Extended-Thunder/send-later/assets/61519252/4a7cc789-042d-4383-a315-6d6872a59fb3)

Changing the minutes shows 20 minutes difference in this case.

And below the minutes on the button are shown one minute ahead and then correctly for the same amount of minutes.
 
![image](https://github.com/Extended-Thunder/send-later/assets/61519252/78349e66-0321-4a46-9dec-e319464095e8)
![image](https://github.com/Extended-Thunder/send-later/assets/61519252/526b3d12-9a01-48ff-80ca-aa05dc2db729)

### How to reproduce

The problem is due to setting the specified time to default and clearing - a few times around. I send a few emails at a specific time, one after another, so I first set an initial time and save as default for two other emails. Then I specify the time to be a minute later for the next two or three emails. Today however I used the button to clear defaults, saved as default again and that's how this happens. Try hitting the clear defaults button more than once, the same for the save as default, but it does happen when clearing and saving two or three times. And it stays stuck like that for the next (Send Later) window.

### Expected behavior

Not clearing the defaults, just saving new defaults when setting a new time, does not produce this but. That's what I did until now and the time was correctly shown in the button every time. So it's the clear defaults button that induces this error.

### Operating System

Kubuntu 

### Operating System Version

23.10

### Thunderbird version

115.9.0 (64-bit)

### Send Later start-up string

Send Later version 10.4.0 on Thunderbird 115.9.0 (20240314154241) [linux x86-64] UI locale en-US, Date Locale pl-PL

**Comment by AndrewPrzelucki** [comment]
I forgot to mention, that despite the incorrect time displayed on the button, when I checked the Send Later schedule list, the times are saved correctly as I picked them. So even though the button displayed incorrect time, the plugin did save the correct time that I picked - that's what the list shows.

**Comment by jikamens** [comment]
This appears to be a date formatting mismatch issue, as [described in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up).
