### ISSUE TITLE
Spell check appearing after sendlater and message disappearing

### ISSUE THREAD

**Issue by tplanter** [Extended-Thunder/send-later#71]
The issue is that Spellcheck is appearing again after the send Later dialog box, and clicking on Send on Spellcheck on the second occasion causes the message to disappear totally.  No sign of it in Drafts, Sent, Outbox. 
Win10 Pro v2004 OS Build 19041.572
Thunderbird v78.4.0 Build ID20201019003438
The email is being sent from a gmail IMAP account.
The steps are:
1. create new message OR edit previous as new message (tried both)
2. click send
3. spell check appears. Click send
4. SendLater appears. Choose any option except Send now (tried 5 minutes and 15 minutes)
5. SendLater disappears and spell check dialog re-appears
6. Click send
7. Message disappears and can't be found anywhere.

Note that choosing Send now sent the message and it appeared in the Sent folder.
[Tbird troubleshoot.txt](https://github.com/Extended-Thunder/send-later/files/5487299/Tbird.troubleshoot.txt)
I've tried this 4 times in the 3 different gmail accounts.

**Comment by jperryhouts** [comment]
Could you check the debug log during this process? -- In Send Later preferences, change log level to "All", then Ctrl+Shift+J opens the debug console. Go through the steps you described here and send any relevant output from the console.

**Comment by tplanter** [comment]
Sorry, you have all output in the attached file including possibly irrelevant.
1. Enabled SendLater
3. Exit Tbird
4. Deleted Unsent Messages folders
5. Restart Tbird
6. Get message about Attempt to resend already sent message.
7. Go offline
8. Create new message and send. Spell check didn't appear 2nd time
9. Go online
10. Message Do I want to send unsent messages? Said later. 
11. Problem message has now appeared in Outbox together with message just created.
[console-export-2020-11-6_10-49-15.txt](https://github.com/Extended-Thunder/send-later/files/5498075/console-export-2020-11-6_10-49-15.txt)

**Comment by tplanter** [comment]
I've now installed send_later-8.1.0-tb.xpi. The issue is still occurring, meaning that check spelling is still appearing for a second time, after the SendLater dialog box. I just press Send and the box disappears.
But the message is going (correctly) to the Drafts folder, with the correct delayed send time, and there appears to be no issue with duplicate messages being sent.

**Comment by jperryhouts** [comment]
Oh, I know what's going on here. When you use 'send does send later', Thunderbird will perform all its usual pre-send checks before notifying send later about the message. But because Send Later can also be started via the toolbar button, it also does those pre-send checks before handling the message, so you'll get bugged about that twice. After #132 this would probably also nag you twice about adding attachments.

I don't have time to fix this right now, but I'll get to it soon. In the mean time it's totally harmless so just click right through it.

**Comment by jperryhouts** [comment]
This should be fixed by #141
