### ISSUE TITLE
S/MIME messages sent more than an hour in the future have invalid signatures

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/send-later#711]
A user writes in email:

>I've finally nailed down that its all my emails sent using Send Later that are showing my S/MIME digital signature (not encryption) as invalid. 
>
>I understand the mechanism I think -- it must be the change to time sent vs the time it's first saved to drafts???
>
>This makes sense although, I did a little testing and found I could send later using the following functions and the cert remained valid:
>
>* 5 minutes from now
>* in 15 minutes
>* in 30 minutes
>* manual set for send in 50 minutes
>
>As soon as I went passed 1 hour, the cert showed as invalid.
>
>I often save emails to send later as much as 48 hours or so prior to sending - like composing on a Friday afternoon for delivery on Monday morning. 
>
>Obviously, it's accepting some amount of wiggle room with the date/time discrepancy - I don't know whether this is wiggle room allowed by the certificate authority or if it's in Send Later.  Is there anyway to adjust the amount of time allowed via Send Later?
>
>Now that I know what's happening, I can open the drafts just before sending and save again, but that pretty much renders Send Later obsolete in this case.  Any ideas or workarounds for this?

**Comment by PetaHub** [comment]
See my issue #683  

https://github.com/Extended-Thunder/send-later/issues/683

**Comment by jikamens** [comment]
Ah yes, this is a duplicate of #683.
