### ISSUE TITLE
TB128 The popup to set the sending time appears empty.

### ISSUE THREAD

**Issue by debba** [Extended-Thunder/send-later#733]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Starting from Thunderbird 128, clicking the "Send Later" button within the sending interface results in an empty popup.

![immagine](https://github.com/user-attachments/assets/4da60e52-8c91-4050-9cc7-cfb032c8692c)

I am currently able to resolve the issue by enabling the "Detach scheduling popup from compose window" option in the add-on settings.

![QmnJ6oU1RHmDUJYlxLxzlg](https://github.com/user-attachments/assets/0d52827d-9edd-467a-841b-7ffa5b41bb27)

### Operating System

Linux

### Operating System Version

Arch Linux (using Wayland)

### Thunderbird version

128.3.0esr

**Comment by jikamens** [comment]
This is a duplicate issue already [documented in the release notes](https://extended-thunder.github.io/send-later/release-notes.html#issue-wayland).
