### ISSUE TITLE
Blank Send Later's Windows

### ISSUE THREAD

**Issue by MPourjam** [Extended-Thunder/send-later#734]
### Prerequisites

- [X] I am reporting a problem, not asking a question (for questions, go to [Discussions](https://github.com/Extended-Thunder/send-later/discussions)).
- [X] I have consulted the [user guide](https://extended-thunder.github.io/send-later/).
- [X] I have consulted the [release notes](https://extended-thunder.github.io/send-later/release-notes.html).
- [X] I have confirmed that I'm running the current version and the problem persists there (note the version number in fine print next to the add-on name [on addons.thunderbird.net](https://addons.thunderbird.net/thunderbird/addon/send-later-3/) and compare it to the version number listed in the add-on details opened from the Add-ons page in Thunderbird; if you've got an old version, click the gear icon and select "Check for Updates").
- [X] If I'm having an issue with date-parsing confusion, I've read the [section about that in the user guide](https://extended-thunder.github.io/send-later/#date-format-confusion-in-the-scheduler-pop-up) and I still think this is something different.
- [X] If I'm having an issue with messages not being delivered, I've followed the [troubleshooting steps in the user guide](https://extended-thunder.github.io/send-later/#messages-dont-send-or-send-multiple-times) and it's still an issue.

### Describe the bug

Windows opened by "Send Later v10.6.0" are blank.
I am using debian 12.7 and GNOME 43.9 and I have installed thunderbird via flatpak and flathub repository.

### How to reproduce

1. Click on "Send Later" when composing an email or 
2. Click on "Send Later" to see list of messages in queue

### Operating System

Debian / GNOME

### Operating System Version

12.6 / 43.9

### Thunderbird version

128.3.1esr (64-bit)

### Send Later start-up string

![image](https://github.com/user-attachments/assets/4cf9e1e1-ef45-4be5-aefe-cc30d724adbc)

**Comment by jikamens** [comment]
You checked "I have consulted the release notes" but you did not, in fact, consult the release notes.

https://extended-thunder.github.io/send-later/release-notes.html#issue-wayland
