### ISSUE TITLE
[8.0.16] Scheduled mail still doesn't leave Thunderbird, remains forever in Draft folder

### ISSUE THREAD

**Issue by PeterCodar** [Extended-Thunder/send-later#85]
A friend is using TB v78.4.1 with the newest "Send Later" v8.0.16 on a IMAP account.
This combination is running on his german Windows 10 Pro with german TB GUI.

He can schedule a mail to send it later. This mail is waiting in the Draft folder (called "Entwürfe" in German). There is no entry in the Outbox folder (called "Postausgang") in the Local Folder (called "Lokale Ordner").
Such a scheduled mail will never leave this Draft folder.

In the previous beta v8.0.15 there was an additional column "später senden" with the scheduled date and time.
This column isn't visibible and not choosable anymore in the newest version.

How can he get this addon working again?
(I help as good as I can to provide you with the nessesary information. Unfortunately, my friend doesn't speak english at all.)

This is the output in the error console for the "send later" button press and enter a new (later) time:

![TB Error console - Scheduling a mail](https://user-images.githubusercontent.com/18629146/98463498-e20c7400-21bb-11eb-9ba7-0ee054952c06.png)

**Comment by jperryhouts** [comment]
This is the same as #16 , but it's disheartening to see it happening still in 8.0.16.

One thing I can suggest off the bat, if you haven't done so already, is just restarting Thunderbird. A missing column in the Drafts folder is a common-ish glitch when a new send later version is installed or upgraded, it is usually resolved when Thunderbird is restarted.

I'm going to close this issue, but I recommend watching #16 for updates about this error, and please do let me know if the Drafts column does not come back after a restart.

**Comment by PeterCodar** [comment]
The Drafts column does NOT come back with 8.0.16.
Not after a TB restart, nor a deinstallation of the addon and TB restart followed by an installation and again a TB restart.

If he tries it with the 8.0.15, the "send later" column appears in Drafts including the scheduled date and time (but the mail never got sent).

I watch #16 for any progress.

**Comment by jperryhouts** [comment]
The problem with the drafts folder column is mysterious. Very little has changed about that part of the code since version 8.0.15. I'm opening a separate issue to track this (#91).
