### ISSUE TITLE
Drafts folder column not appearing in 8.0.16

### ISSUE THREAD

**Issue by jperryhouts** [Extended-Thunder/send-later#91]
User reported in #85 that the drafts folder column worked in 8.0.15, but does not work in 8.0.16, even after restarting, reinstalling, etc.

This is really mysterious, because very little has changed about the drafts folder column since 8.0.15. I'm opening this issue so this doesn't slip through the cracks, but if anyone else is experiencing this please comment here with any relevant information that might help me reproduce this behavior.

**Comment by PeterCodar** [comment]
Excellent news:
With your newest [send_later-8.0.16-tb.zip](https://github.com/Extended-Thunder/send-later/files/5507414/send_later-8.0.16-tb.zip) the "send later"-column is back in the Drafts folder
**AND EVEN BETTER**
your addon works now as expected, scheduled mails will be sent!

Whatever you have done, it works! 👍
Thank you very much for your support.

**Comment by jperryhouts** [comment]
Very glad to hear it!

**Comment by jperryhouts** [comment]
Got a similar report from another user, for whom the issue is persisting with the newest release. Opening this issue back up until that is resolved.

**Comment by jperryhouts** [comment]
Okay, I think this should be fixed for real by #97 . Looks like it was a security policy violation that was blocking the drafts column overlay from loading. I still don't understand why this appeared when it did, and only for a subset of users.
