### ISSUE TITLE
Send Later moves mail to Drafts and doesn't send

### ISSUE THREAD

**Issue by banegold** [Extended-Thunder/send-later#98]
I use mail merge in addition to the send later and before it would move the mail to my local folders in the outbox and prepare them for sending. Now it moves them to drafts in my actual gmail account and is never sent. What do I need to do to fix this? Thanks!

**Comment by jperryhouts** [comment]
Please be (much) more specific. What version are you using? What does "before" mean? What is your specific use case? Do you want messages to go directly to your outbox, or to be scheduled for sending at a specified time in the future?

**Comment by banegold** [comment]
I think I fixed it! Will affirm tomorrow if my batch goes out successfully!

**Comment by jperryhouts** [comment]
Great. I'm going to close this issue for now, but let me know if you're still encountering problems.
